### ISSUE TITLE
Switching desktop issue

### ISSUE THREAD

**Issue by hanckmann** [redox-os/orbtk#105]
**Describe the bug**
When starting an orbTK application, then change desktop, the orbTk application becomes black. It will only update upon a trigger (clicking a button or resizing the window).
Note that clicking a button while not seing the button is a real challenge

**To Reproduce**
1. Start application
2. Switch to other desktop
3. Switch back to the desktop on which the application was started

**Expected behavior**
The original widgets and colors should be rendered when switching back to the desktop.

**Screenshots**
The screenshot shows the same application started twice. Both where black when switching back to the desktop, but I clicked a button on the right application.

![Screenshot_2019-12-06_11-07-08](https://user-images.githubusercontent.com/925657/70315194-5b1b8280-1819-11ea-8cf5-a0757c7a9fa2.png)

Note; there is also a black square on the right image, this is where the screenshot application was just before taking the screenshot.

**Desktop (please complete the following information):**
I am on ArchLinux
```
λ ~/ uname -a
Linux copernicus 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux

```
I run Xfce4 with i3 as wm on Xorg with Intel:

- xf86-video-intel 1:2.99.917+897+g0867eea6-
- extra/xorg-server 1.20.6-1
- xfce4 4.14.0-1
- i3-wm 4.17.1-1

**Comment by FloVanGH** [comment]
@hanckmann I had the same issue today, because I've tested for the first time a tilling window manager and I really like it, thank you 😃. On the next days I will evaluate winit as window backend, maybe this would fix some issues. I keep you updated.

**Comment by DaniellMesquita** [comment]
@FloVanGH could XFCE4 be installed in RedoxOS, as it supports its own libc?

**Comment by FloVanGH** [comment]
@DaniellMesquita you should ask this in the Redox chat https://redox-os.org/community/.

**Comment by FloVanGH** [comment]
@hanckmann could it closed=
