### ISSUE TITLE
Text resizing

### ISSUE THREAD

**Issue by hanckmann** [redox-os/orbtk#111]
**Describe the bug**
When resizing a window, the text block font size also changes.

**To Reproduce**
Start the "My first OrbTk app".
Resize the window.

**Expected behavior**
The window should resize, but the content should remain in tact.

**Screenshots**
![large](https://user-images.githubusercontent.com/925657/70375251-e40aea80-18fb-11ea-9dc3-d652a3bc404c.png)
![small](https://user-images.githubusercontent.com/925657/70375252-e79e7180-18fb-11ea-8a72-886a1fb5f56b.png)
These screenshots show the large window and the smaller (resized) window. In the latter the text is not readable anymore.
Also note the destortion. The bug report for this issue is already provided at #105 (or at least seems similar to that issue).

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Comment by FloVanGH** [comment]
I think it could also be related to the minifb resize bug. There is an new update. I will check it today.

**Comment by FloVanGH** [comment]
Should be fixed.
