### ISSUE TITLE
load external font

### ISSUE THREAD

**Issue by darkskygit** [redox-os/orbtk#115]
# Context

currently orbtk uses the built-in Roboto font, and it is load using register_font in `Application::new().window()`, but it looks like there is no way to add fonts from the external and skip built-in font loading

# Problem description & Solution

built-in font do not contain CJK characters, need a way to load font from outside

# Examples and MockUps

load parameter font from window widget?

``` rust
        let font = world
            .entity_component_manager()
            .component_store()
            .get::<HashMap<String, PathBuf>>("font", window)
            .unwrap()
            .clone();
        for (name, path) in font {
            window_shell
                .borrow_mut()
                .render_context_2_d()
                .register_font(&name, path);
        }
```

**Comment by FloVanGH** [comment]
Would be make sense to register / load fonts by the window widget. There you have a central place to do it. An alternative could be do register / load the fonts with a theme.

**Comment by ecreeth** [comment]
Maybe this can help [font-kit](https://github.com/servo/font-kit)
