### ISSUE TITLE
Weird String16::push

### ISSUE THREAD

**Issue by Ltrlg** [redox-os/orbtk#120]
Looking at the documentation of `String16::push`, I found both its documentation and implementation weird

As of 53c7d6fe, it looks as follows:
```rust
/// Appends a given string slice onto the end of this `String16`.
pub fn push(&mut self, ch: char) {
    self.utf16.push(ch as u16)
}
```

  - First (which is what bring me looking at the implementation), calling “slice” a `char` is wrong.
  - Second, there is nothing preventing `char` from containing a non-BMP value, which would get truncated by the cast.
    - This means using this method with emojis could lead to another character being actually stored.
    - Not sure whether there are such characters in non-BMP already, but it could even lead to invalid UTF-16 being stored.

**Comment by FloVanGH** [comment]
Yes the String16 struct needs a little bit love. Thank you for the hint. I think we should fix this issue soon. I also want to provide a better compatibility to the default  String.

**Comment by Ltrlg** [comment]
This specific issue is fixed. I will continue to work on String16 and open new issues/PR as needed.
