### ISSUE TITLE
Procedurally derive new and setter methods for types

### ISSUE THREAD

**Issue by mmstick** [redox-os/orbtk#121]
Procedural macros that could eliminate a lot of the boilerplate that we are currently doing by hand.

- [derive-new](https://github.com/nrc/derive-new)
- [derive_setters](https://github.com/Lymia/derive_setters)

**Comment by FloVanGH** [comment]
@mmstick do you want to do it, otherwise I can do it next.

**Comment by mmstick** [comment]
I'm currently busy with Pop Shell at the moment.

**Comment by FloVanGH** [comment]
Maybe we should avoid using more procedural macros. OrbTk uses macros and proc macros a lot and I'm worry it has an impact on the compile time. Therefore I close this for now.
