### ISSUE TITLE
Replace String16 with std::string::String

### ISSUE THREAD

**Issue by Ltrlg** [redox-os/orbtk#128]
> String16 struct needs a little bit love.

… said @FloVanGH. Let’s look at what is needed.

  - [ ] “bytes” is technically correct for `u16` but quite unusual. Should `String16` stick with it or use more appropriate wording? The selected option should be documented.
  - [ ] `String16::as_bytes_mut` allows storing invalid UTF-16. If the contract of the class is to store valid UTF-16, then it should be tagged `unsafe`. The selected contract should be documented.
  - [ ] Identify methods of `std::String` that should be implemented by `String16`.
  - [ ] Methods that may break when working with non-BMP chars (somewhat depends on contract):
    - [ ] `insert_str` (may insert inside a surrogate pair)
    - [x] #120 `push` (value truncated)
    - [ ] `remove` (may remove half of a surrogate pair)
  - [ ] Ensure there are tests for existing behavior & fixed bugs

@FloVanGH Please add anything you see that I may have forgotten.

**Comment by FloVanGH** [comment]
Any updates?

**Comment by kivimango** [comment]
String16 does not implement the Iterator trait, therefore one cannot iterate over the contents.

**Comment by smmalis37** [comment]
So I'm new to OrbTK, and this may be documented elsewhere, but why not just use the built in String? What advantages does UTF-16 have that make its use necessary? It would be a large ergonomics improvement if standard Strings could work instead imo.

**Comment by FloVanGH** [comment]
I had problems with default String type on text input. Because some signs like `ä` or `ö`will be count as two signs. That is complicated e.g. by positing the text cursor. In the String16 struct the length of `ä`  and `ö` is also 1 as `a` and `o`.

**Comment by smmalis37** [comment]
Wouldn't using something like [unicode-segmentation](https://crates.io/crates/unicode-segmentation) and its support for grapheme clusters handle all that?

**Comment by FloVanGH** [comment]
Thank you for the hint. I will check it, maybe it could be a solution.

**Comment by smmalis37** [comment]
Also, UTF-16 will still treat some signs as multiple characters, for example: 🤦🏼‍♂️. That one emoji is 7 UTF-16 code units.

**Comment by JerwuQu** [comment]
I also think opting for std::string::String instead would be preferred

**Comment by FloVanGH** [comment]
I’m on it. I found a way how we could use standard String. I let you know when it’s done.

**Comment by FloVanGH** [comment]
done. you can now use default `String` instead of `String16`.
