### ISSUE TITLE
How to get TextBox state in main

### ISSUE THREAD

**Issue by joefiorini** [redox-os/orbtk#130]
I’m trying to write an app that does the following:

1. Gets launched from a command line interface
2. Shows a window with a textbox and button
3. When the button is clicked it hides the window, prints the text from the box to stdout, hides the window & exits

One approach would be to print the value in the update when the button is clicked, but that won’t be very flexible for additional use cases I’ll have in the future. Also I don’t think the update function should have side effects like printing to stdout.

So I’m trying to figure out the way to get the “text” property out of the MainView’s state in the window create closure. What is the correct way to get the state outside the update function at the top level?

**Comment by FloVanGH** [comment]
You could try to insert a closure as property in the root child of the window. And access that closure in the update method.

e.g.

```rust
Window::create().child(MainView::create().do(|| ...).build(ctx)) ...
```

You could also register a service in the registry that handles your code. The registry is also accessible inside of the states.

**Comment by joefiorini** [comment]
Thanks for the reply! I feel dense, but I've been scouring the docs, source code & examples and can't figure out for the life of me how to register a custom service. I can see where a `registry` is created when I call `Application.window` (and contains the `settings` service) but that registry doesn't seem to be passed to anything I have access to. I can also see in `State::update` where I have access to the `registry`, but not anywhere outside of that. Are there any examples I'm missing that show how to register a _custom_ service?

**Comment by FloVanGH** [comment]
There is also an `init` method that could be implemented for State. It will called only one time after the widget is created. There you could register your service like `registry.register("my_service", MyService::default());`
