### ISSUE TITLE
How to make Canvas update continuously

### ISSUE THREAD

**Issue by FredericaBernkastel** [redox-os/orbtk#132]
I've been stuck there for 3 days. 
`examples/canvas.rs` tells how to make canvas render on button click, but i have a long running thread defined in main. It draws a new image 60 times a second into static framebuffer. Then in `RenderPipeline::draw` function of the canvas, i can read data from the framebuffer.
The only problem, how to make canvas redraw automatically when new data is ready?
I can't find any documentation how i can possibly do that.

**Comment by FloVanGH** [comment]
Unfortunately this is not possible at the moment. The only way to trigger redraw is an event. One of the next topics is to introduce ways to easily handle tasks in other threads and async task. We also want to implement a signal mechanism that could also trigger a redraw.

But I think I have a temporary solution how I could help you with your problem. Is it possible that you share the code with me? Then I could check it.

**Comment by FredericaBernkastel** [comment]
Yes, it's [OpenCL GPU renderer](https://github.com/FredericaBernkastel/OpenCL_Attractor-rust). I'm new to rust, do you want me to provide a simplified example?

**Comment by FredericaBernkastel** [comment]
Done. Pressing "render" button will just update gui, render thread works all the time.
https://gist.github.com/FredericaBernkastel/7e342621ac097721101fc4f655c9634f

**Comment by FloVanGH** [comment]
Ok nice. I'll look at it tomorrow.

**Comment by FloVanGH** [comment]
Sorry for my delayed answer. I want to finish one topic and after that I will check your code and will provide a basic way to request redraw.

**Comment by FloVanGH** [comment]
It is now possible to sent an update request.

This works now:

```rust
use orbtk::{prelude::*, render::platform::RenderContext2D, shell::ShellRequest};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::Duration;

static mut IMAGE_BUFFER: Option<Arc<Mutex<Vec<u32>>>> = None;

// OrbTk 2D drawing
#[derive(Clone, PartialEq, Pipeline)]
struct Graphic2DPipeline;

impl render::RenderPipeline for Graphic2DPipeline {
  fn draw(&self, render_target: &mut render::RenderTarget) {
    let width = render_target.width();
    let height = render_target.height();
    let mut render_context = RenderContext2D::new(width, height);

    unsafe {
      if let Some(image_buffer) = &IMAGE_BUFFER {
        let image_buffer = image_buffer.lock().expect("mutex is poisoned");
        let image =
          Image::from_data(512, 512, image_buffer.clone()).expect("imagebuffer is corrupted");
        render_context.draw_image(&image, 0.0, 0.0);
        render_target.draw(render_context.data());
      }
    }
  }
}

#[derive(Default, AsAny)]
struct MainState {
  thr: Option<thread::JoinHandle<()>>,
}

impl State for MainState {
  fn init(&mut self, _: &mut Registry, ctx: &mut Context) {
    let sender = ctx.request_sender();

    self.thr = Some(thread::spawn(move || {
      let mut scalar = 0u32;
      loop {
        unsafe {
          let vec = vec![0xFF000000u32 | scalar; 512 * 512];
          if let Some(image_buffer) = &IMAGE_BUFFER {
            let mut image_buffer = image_buffer.lock().expect("mutex is poisoned");
            *image_buffer = vec;
          }
          scalar += 1;
          sender.send(ShellRequest::Update).unwrap();
          thread::sleep(Duration::from_millis(16));
        }
      }
    }));
  }
}

widget!(MainView<MainState>);

impl Template for MainView {
  fn template(self, _: Entity, ctx: &mut BuildContext) -> Self {
    self.name("MainView").child(
      Canvas::create()
        .attach(Grid::row(1))
        .render_pipeline(RenderPipeline(Box::new(Graphic2DPipeline {})))
        .build(ctx),
    )
  }
}

fn main() {
  unsafe {
    IMAGE_BUFFER = Some(Arc::new(Mutex::new(vec![0xFF000000u32; 512 * 512])));
  }

  Application::new()
    .window(|ctx| {
      Window::create()
        .title("OrbTk - canvas example")
        .position((100.0, 100.0))
        .size(512.0, 512.0 + 46.0)
        .child(MainView::create().build(ctx))
        .build(ctx)
    })
    .run();
}

```

**Comment by FredericaBernkastel** [comment]
Thanks, it works! :heart:

**Comment by FloVanGH** [comment]
You're welome

**Comment by FloVanGH** [comment]
You're welcome

**Comment by FloVanGH** [comment]
You're welcome 🙂.

**Comment by DevAlone** [comment]
@FloVanGH, `request_sender` doesn't seems to exist on `Context`. Has something changed in the code?

**Comment by ghost** [comment]
@DevAlone yes it is removed. You can use `ctx.send_window_request(WindowRequest::Redraw)`.
