### ISSUE TITLE
Examples: 7-11% idle CPU Load 

### ISSUE THREAD

**Issue by justinwilaby** [redox-os/orbtk#136]
**Describe the bug**
Running `cargo run --example widgets --release` produces a UI with an idle CPU load ranging from 7-11%.

It appears that `State#update` is called continuously even when no state changes have occurred. I'm not sure if these calls are necessary but wanted to bring this to your attention. Idle CPU loads are generally indicative of defects and are non-starters for projects intended for devices with limited resources. 

**To Reproduce**
1. `cargo run --example widgets --release`
2. View cpu loads on running processes 

**Expected behavior**
Near zero CPU load when window is backgrounded or widgets are not being interacted with.

**Screenshots**
<img width="820" alt="image" src="https://user-images.githubusercontent.com/2652885/71739463-5e9d2c00-2e0e-11ea-996b-7013a52d1848.png">

**Desktop (please complete the following information):**
<img width="589" alt="image" src="https://user-images.githubusercontent.com/2652885/71739511-7d9bbe00-2e0e-11ea-8d7c-f54de1104009.png">

**Comment by FloVanGH** [comment]
Thank you for the report. This will be optimized soon.

**Comment by FloVanGH** [comment]
Related to #158

**Comment by FloVanGH** [comment]
I optimized the update rate of minifb, that should reduce the idle CPU load of OrbTk. At next I will implement polling.
