### ISSUE TITLE
Frameless window support request

### ISSUE THREAD

**Issue by MiyamuraMiyako** [redox-os/orbtk#140]
# Context
I want to self define Window frame.

# Problem description & Solution
I have no idea.

# Examples and MockUps
Window::create()
    ......
    .frame(false)
    .build(ctx);

**Comment by FloVanGH** [comment]
Good point. Also a feature I want 😄. Thank you for the request.

**Comment by valkum** [comment]
See #169

**Comment by FloVanGH** [comment]
MR is merged.
