### ISSUE TITLE
[Web] Window does not change its size automatically

### ISSUE THREAD

**Issue by afonichev** [redox-os/orbtk#141]
When you change the size of the browser window, nothing happens. When the page is reloaded, the new sizes are applied.

How to fix it?

```
use orbtk::prelude::*;

fn main() {

    orbtk::initialize();

    Application::new()
        .window(|ctx| {
            Window::create()
                .title("Demo")
                .resizeable(true)
                .child(TextBlock::create()
                    .text("Hello world!")
                    .vertical_alignment("center")
                    .horizontal_alignment("center")
                    .build(ctx))
                .build(ctx)
        })
        .run();
}

```

![image](https://user-images.githubusercontent.com/15726637/72345210-2b974a00-36e4-11ea-8068-6e24103f6acc.png)

Reducing the size of the browser window

![image](https://user-images.githubusercontent.com/15726637/72345233-3baf2980-36e4-11ea-8c6d-f1621e4b4028.png)

Reloading page and increasing the size of the browser window

![image](https://user-images.githubusercontent.com/15726637/72345409-c7c15100-36e4-11ea-99b7-1c36228b4b0d.png)

**Comment by FloVanGH** [comment]
This is a bug. It should also resize with the browser window. I should be not complicated o fix it. I let you know after it’s done.

**Comment by afonichev** [comment]
> This is a bug. It should also resize with the browser window. I should be not complicated o fix it. I let you know after it’s done.

Thanks.

**Comment by FloVanGH** [comment]
Fixed.
