### ISSUE TITLE
[Proposal] OS crates separation

### ISSUE THREAD

**Issue by ecreeth** [redox-os/orbtk#142]
First, I am not an expert in `Rust` and I do not know how they plan to structure this project when supporting` android`, `ios` and `ubuntu touch` natively.

I think it would be good to separate the different platforms in crates, this is useful for people with little knowledge in `Rust` and who want to contribute to this project. :smile: I hope it helps. Also, I think it would be good to separate in **features** the crate of `orbtk-widgets` for conditional compilation

#### Posible solution

| Crate Name | Include by default | 
| ---------------- | ---------- |
| `orbtk-redox-os` | :heavy_check_mark:  Internal crate
| `orbtk-windows` | :heavy_check_mark:  Internal crate
| `orbtk-linux` |  :heavy_check_mark:  Internal crate
| `orbtk-shared` |  :heavy_check_mark:  Internal crate
| `orbtk-web` | :package:  External crate
| `orbtk-android` | :package:  External crate
| `orbtk-ios` | :package:  External crate
| `orbtk-ubuntu-touch` | :package:  External crate

**Comment by MagixInTheAir** [comment]
Maybe an `orbtk-core` crate, along with `orbtk-platform-XXX` would make sense. Or keep everything in a single crate but refactor the code to clearly decouple the core and platform-dependant code

**Comment by FloVanGH** [comment]
Thank you fore your input. The current structure is created with the intention to be modular, to have multiple single crates that could be used also independent for other projects. This is the current crate structure:

* api: base api elements of OrbTk e.g. widget and application parts
* css-engine: parse and read values from a css file
* proc-macros: procedural helper macros
* render: cross platform 2D/3D render library
* shell: cross platform window and event handling
* theme: OrbTks default theme (light and dark)
* tree: tree structure based on DCES
* utils: helper structs and traits
* widgets: base widget library

Only the render and shell crates contains platform specific code. But soon I could be possible that OrbTk does not more includes platform specific code only its dependencies. Therefore I think a crate structure like you suggested is not needed.
