### ISSUE TITLE
font_size takes no effect when appending child via Context

### ISSUE THREAD

**Issue by Zwo1in** [redox-os/orbtk#145]
**Describe the bug**
As in title, no matter what font size I specify when creating new TextBlock, the outcoming font size does not vary.

**To Reproduce**
```rust
struct FooState {
    action: Option<FooAction>,
    messages_count: RefCell<usize>,
}

impl FooState {
    fn action(...) {...}

    fn push_msg(&self, ctx: &mut Context, message: String) {
        *self.messages_count.borrow_mut() += 1;
        let messages_stack = ctx.entity_of_child("messages")
            .expect("Failed to acquire entity of messages stack");

        let message_entity = TextBlock::create()
            .text(String16::from(message))
            .font_size(5.0)
            .selector(Selector::from("text-block")
                .id(format!("message_{}", *self.messages_count.borrow())))
            .horizontal_alignment("start")
            .vertical_alignment("start")
            .build(&mut ctx.build_context());

        ctx.append_child_entity_to(
            message_entity,
            messages_stack,
        )
    }
}

widget!(
    FooView<FooState> {
        started: bool
    }
);

impl Template for FooView {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("FooView")
            .child(
                Stack::create()
                    .orientation("vertical")
                    .selector(Selector::from("stack").id("messages"))
                    .build(ctx),
            )
            .build(ctx),
    }
}
```

Then call push_message from update function with different font_size. I've also tried with `append_child_to` without using `build` on `message_entity` and the effect is the same

**Expected behavior**
I expected to be able to change font_size in appended widgets.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - no browser
 - Version: 1903
 - latest branch `develop`  as for 18.01.2020

**Comment by FloVanGH** [comment]
Thank you for the report. I will check it.

**Comment by jpoles1** [comment]
I think I'm experiencing a similar issue with buttons, the chaining of a font_size() doesn't seem to impact the size of the text. 

Unsure if related, but I'm also having some problems getting size/width/height to behave as expected, these properties also seem to be ignored at times on buttons (perhaps when they're trying to shrink smaller than the font size in the button?)

**Comment by Zwo1in** [comment]
I just realized that when I append TextBlocks into Container, not directly to the stack, the issue is gone. It works like a charm with this modification:

```rust
let message_entity = Container::create()
    .height(50.0)
    .selector(Selector::from("container")
        .id(format!("message_{}", self.messages_count.borrow().to_string())))
    .child(TextBlock::create()
        .text(String16::from(message))
        .font_size(15.0)
        .margin((5.0, 10.0, 0.0, 0.0))
        .horizontal_alignment("start")
        .vertical_alignment("start")
        .build(&mut ctx.build_context()),
    )
    .build(&mut ctx.build_context());
```

**Comment by FloVanGH** [comment]
The problem is that properties set in OrbTk has the highest priority and overwrite the properties set in Rust.

What you could to is to set the Selector of the widget to default.

`TextBlock::create().selector(Selector::default()).font_size(15.0).build(ctx)`

**Comment by FloVanGH** [comment]
@Zwo1in can it closed?

**Comment by Zwo1in** [comment]
It's up to you :) I managed the way around as I said in my last comment.

**Comment by MCOfficer** [comment]
Neither the proposed solution (idk why) nor the workaround (`Selector` is gone) worked for me. However, you can get a bit cheesy with custom CSS:

```rust
let child = TextBlock::create()
		.class("log-line")
		.text(msg);
```
```css
.log-line {
    font-size: 12 !important;
}
```
