### ISSUE TITLE
Contributing new widgets: Numeric Input

### ISSUE THREAD

**Issue by jpoles1** [redox-os/orbtk#146]
# Context
I'm currently using OrbTk to build a simple GUI for a small tool I'm working on. In the process, I've been creating some simple widgets like a numeric input (text block with + and - buttons). 

# Problem description & Solution
There are not very many widgets currently available. I'm wondering if the maintainers are currently interested in new widget contributions from the community, such as that described above.

 Is the repo currently in a stable enough state for this to even be worthwhile? Is there any plan/desire to create a repo/library of community built widgets?

PS: I would normally have asked these questions on the chat server, but I have not yet been granted access 😄

**Comment by FloVanGH** [comment]
Sure all sort of contributors are welcome 🙂. Yeah I think OrbTk is stable enough for this sort of contribution. If you like you could created an PR and I would be happy to review it.

See you on the chat 😉.

**Comment by FloVanGH** [comment]
Any update?

**Comment by kivimango** [comment]
![numeric_input_preview1](https://user-images.githubusercontent.com/18540032/81195210-d4342700-8fbd-11ea-8e5b-54cb751ab445.jpg)
It needs tweaking, but it is working.

**Comment by FloVanGH** [comment]
@kivimango nice 🙂

**Comment by kivimango** [comment]
#211

**Comment by kivimango** [comment]
#211 is merged, can we close it?
