### ISSUE TITLE
Support CSS compatible with GTK

### ISSUE THREAD

**Issue by DaniellMesquita** [redox-os/orbtk#147]

**Comment by FloVanGH** [comment]
We thought about a GTK css to OrbTk css converter.

**Comment by DaniellMesquita** [comment]
?

It isnt just CSS?

**Comment by FloVanGH** [comment]
GTK uses its own property and selector names. We need to map the GTK names to OrbTk names.

**Comment by FloVanGH** [comment]
We switched to a new style format, therefore this will not be possible now.
