### ISSUE TITLE
Attach function to window close

### ISSUE THREAD

**Issue by duncanrhamill** [redox-os/orbtk#148]
Hi, I've run into a situation where I'd like to have my `State`'s update function called periodically rather than just when an event occurs, which I've implemented similarly to #132 with a background thread requesting a `ShellRequest::Update` every 30 Hz. 

I'd like an easy way of cleaning up this thread once the user closes the window, but I'm not sure about how to do latch onto the `SystemEvent::Quit` event to be able to do this, do you have any ideas?

**Comment by FloVanGH** [comment]
As alternative I could add a `clean_up` method to the `State` trait. Then you could register and clean your thread in the main state. What do you think?

**Comment by FloVanGH** [comment]
done!
