### ISSUE TITLE
Widget (selector) ID is too easy to accidentally erase

### ISSUE THREAD

**Issue by merehap** [redox-os/orbtk#149]
It should be easy and intuitive to repeatedly change the styling associated with a (ID-indexed) widget, but currently if you call

`ctx.child(id).set("selector", selector);`

it will wipe out the ID of the widget/selector. If you then try to set the selector a second time, you'll get an unwrap panic on `child` because the previous set call overwrote the entire selector, ID included. You need to manually store then reset the ID every time you update the selector, which is a hassle and counter-intuitive (I just wasted hours trying to figure out what was going on).

Now if the ID in question was only a CSS selector ID, then the current behavior might make sense. But since ID doubles as the standard way to access a widget, I think a change of behavior is warranted if possible.

Side note: it would be nice if that `unwrap` was an `expect` instead. A useful error would save the human context-switch of flipping to the documentation of `child`.

**Comment by FloVanGH** [comment]
Thank you for your input. What would be nice is a way to extend / edit the current selector. I will think about a solution.

> Side note: it would be nice if that unwrap was an expect instead. A useful error would save the human context-switch of flipping to the documentation of child.

Good point.

**Comment by FloVanGH** [comment]
Related MR #159

**Comment by FloVanGH** [comment]
I've updated the api of the selector:

```rust
// from
Button::create().selector(Selector::from("button").class("primary").id("my_id"). ...

// to
Button::create().element("button").class("primary").id("my_id"). ..
```
