### ISSUE TITLE
How to use ToggleButton's `pressed` flag with `on_click`?

### ISSUE THREAD

**Issue by shadiakiki1986** [redox-os/orbtk#151]
I'm looking at [examples/widgets.rs#L200](https://github.com/redox-os/orbtk/blob/443d8b17a29dc26c0dd2bc4d7c0423d9f6a271b6/examples/widgets.rs#L200).
What I'd like to do is get the ToggleButton's status (pressed or not) and take an action accordingly.
Something along the lines of 
```
...
.child(
ToggleButton::create()
  .text("ToggleButton")
  .on_click(move |states, _| -> bool{ 
    if pressed { // <<<<< Need help here
      state(id, states).action(...);
    } else {
      state(id, states).action(...);
    }
  })
  .margin((0.0, 8.0, 0.0, 0.0))
  .attach(Grid::column(0))
  .attach(Grid::row(3))
  .build(ctx),
)
...
```

How can the `if pressed` condition be implemented?

I tried to figure it out and can guess that it's something along the lines of [src/switch.rs#L105](https://github.com/redox-os/orbtk/blob/443d8b17a29dc26c0dd2bc4d7c0423d9f6a271b6/crates/widgets/src/switch.rs#L105): `states.get_mut::<SwitchState>(id).toggle_selection();`, but I couldn't figure it out yet.

Edit: added `state(...).action(...)` to example

**Comment by FloVanGH** [comment]
The ToggleButton has a `on_changed` callback. It is triggered after `is_pressed` is changed. 

You could check the value of the ToggleButton in the states update method:

example:

```rust
  fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
        if let Some(action) = self.action {
            match action {
                Action::Changed => {
                    if *ctx.widget().get::<bool>("is_pressed) {
                        // do stuff
                   }
                }
       }

...

ToggleButton::create()
    .on_changed(move |states, _| {
        states.get_mut::<MainState>(id).action(Action::Changed);
    }
...
```
