### ISSUE TITLE
example/widgets.rs: Executable size jump from 2MB to 17MB

### ISSUE THREAD

**Issue by shadiakiki1986** [redox-os/orbtk#152]
I noticed that the executable size for `cargo build --example widgets --release` jumps

- from ~2MB for 0.3.1-alpha1 with rustc 1.37
- to ~17MB for 5cb3649 (latest commit 20 days ago) with rustc 1.41

Not sure if this means anything, but I thought I'd bring it up anyway just in case it's important.

**Comment by brmmm3** [comment]
I've noticed the same. But it's not a matter of the Rust version and the increase seemed to happen much earlier.

**Comment by VestniK** [comment]
`.rodata` section of the release executable jumps from 500Kb to 12Mb in a9653954fed7275328bc8e893c3465506154571e (this commit embeds ~12Mb font file `OpenMoji-Color.ttf` into `theme` crate)

**Comment by FloVanGH** [comment]
Thank you for your research. OpenMoji is not yet used in OrbTk, I will remove it.

**Comment by FloVanGH** [comment]
Remove openmoij font.
