### ISSUE TITLE
How to use a trait in the application?

### ISSUE THREAD

**Issue by shadiakiki1986** [redox-os/orbtk#153]
My goal is to build a GUI that accepts any object that implements a particular trait.
I wrote the gist [here](https://gist.github.com/shadiakiki1986/bd5c705b627fb82f8aba89047b050330) based on `examples/clear.rs` to illustrate. The main modifications are for having a trait member called `summary`.
It throws 2 main compiler errors:

```
widget!(MainView<MainViewState> {
    text: String16,
    summary: Summary // doesn't have a size known at compile-time
});
```
and
```
ctx.widget().get::<Summary>("summary"); // trait not allowed
```

If `Summary` is replaced with `&Summary` in the widget, then it throws the error "no rules expected this token in macro call".
I realize that the errors themselves are rust-related and not orbtk-related, so it's likely that I'm just doing this "not the orbtk way".

What's the proper way to implement this with orbtk?

**Comment by FloVanGH** [comment]
I had the same issue on the Canvas widget and could solve it with a trick. I've wrapped the trait object inside of a struct.

You could check:

* https://github.com/redox-os/orbtk/blob/develop/crates/api/src/properties/widget/render_pipeline.rs
* https://github.com/redox-os/orbtk/blob/develop/crates/widgets/src/canvas.rs
