### ISSUE TITLE
ImageWidget without write a file

### ISSUE THREAD

**Issue by stephaneworkspace** [redox-os/orbtk#154]
# Context

I search to pass image without writing file with image like this:
````
.child(ImageWidget::create().image(OUTPUT).build(ctx))
````

OUTPUT need to be a file on my hard drive

but it's demand a write 

# Problem description & Solution

Solution: Use Image::
````
Image::from_data(width, height, raw_final);
````
but I don't find in the doc how to pass Image in ImageWidget

Thank you for your work !

**Comment by FloVanGH** [comment]
That is not yet possible. I will work on it soon. Thank you.

**Comment by FloVanGH** [comment]
done! documentation included.

**Comment by MCOfficer** [comment]
Can we get more of these convenience functions for other common types, e.g. `[u8]` or [`ImageBuffer`](https://docs.rs/image/0.23.3/image/struct.ImageBuffer.html)]? I imagine the common usecase is to bundle images via `include_bytes!`, which returns a `[u8; ?]` - and converting that to a proper `Vec<u32>` sucks.

For reference, my approach:
```rust
fn header_image() -> Vec<u32> {
    let array: &[u8] = include_bytes!("../assets/header.jpg");
    let img = image::load_from_memory_with_format(array, image::ImageFormat::Jpeg).unwrap();
    img.into_rgba()
        .pixels()
        .map(|p| {
            ((p[3] as u32) << 24) | ((p[0] as u32) << 16) | ((p[1] as u32) << 8) | (p[2] as u32)
        })
        .collect()
}
```

it's especially bugging me that support for this [already exists](https://github.com/redox-os/orbtk/blob/develop/crates/render/src/raqote/image.rs#L48-L53), just hidden under the hood.
