### ISSUE TITLE
Struct orbtk::TextBlock doesn't appear to have "Word Wrapping"

### ISSUE THREAD

**Issue by rdearman** [redox-os/orbtk#156]
# Context

At the moment the Struct orbtk::TextBlock seems like it should really be called a Label, since it only seems to support one line of text. 

# Problem description & Solution

I don't have a solution. But my problem is that I wanted to render some text which I would use as a sort of Message Center for the user. I'm trying to do a simple game, and I would like to use something like TextBlock to give information to the Player. But this information would be more than one line, but I don't know it in advance. For example:

"Poker is a fascinating, easy-to-learn game that has surged in popularity since the turn of the millennium. While different variants and types of poker can be played, the basic poker rules usually stay consistent from one form to the next."

# Examples and MockUps

.child( TextBlock::create()
							.text("Good afternoon Player 1, Poker is a fascinating, easy-to-learn game that has surged in popularity since the turn of the millennium. While different variants and types of poker can be played, the basic poker rules usually stay consistent from one form to the next. ")
							.width(370.0)
							.height(370.1)
							.wordwrap(true)
							.margin(4.0)

                            .build(ctx)
                    )

**Comment by FloVanGH** [comment]
Word wrapping and trimming is not yet implemented in OrbTk. After it is the `TextBox` will provide it.
