### ISSUE TITLE
Unnecessary wakeup

### ISSUE THREAD

**Issue by sfanxiang** [redox-os/orbtk#158]
**Describe the bug**
orbtk calls `update` on minifb in a tight loop:
https://github.com/redox-os/orbtk/blob/54301bcc796c9ba1812f78528c91b93a24b9877c/crates/shell/src/minifb/mod.rs#L361-L382

However, `minifb::Window::update` unconditionally wakes up after the amount of time for update rate elapses, instead of waiting for actual events to happen.

So even if orbtk stays in low CPU usage, it still consumes CPU from time to time.

On linux, you can find an orbtk program to be in `nanosleep` most of the time. For comparison, a typical gtk program spends most time in `poll`. Even firefox stays in `poll`, `pthread_cond_wait`, and `pthread_cond_timedwait` most of the time.

This is similar to #136, but I believe this is still a problem independent of how #136 is resolved.

**To Reproduce**
Steps to reproduce the behavior (linux):
1. Run an orbtk program
2. Attach the debugger
3. You'll likely end up in a `nanosleep` with only a short amount of time before it wakes up.

**Expected behavior**
Actually polling the input events we're waiting for.

**OS**
Linux, but the problem should be universal.

**Comment by FloVanGH** [comment]
Thank you very much. Some architectural changes are needed in OrbTk to archive that. The wake up need to be called from window events and custom events that could come from a background thread. The next big topic would be better mechanisms to support async functions and custom threads https://gitlab.redox-os.org/redox-os/orbtk-mirror/issues/215. I will use this topic also to implement `poll` in OrbTk.

**Comment by FloVanGH** [comment]
Should be fixed.
