### ISSUE TITLE
Help wanted with checkbox widget

### ISSUE THREAD

**Issue by Fenex** [redox-os/orbtk#160]
Hi. I play with orbtk and stuck for 3 days.

I wrote a simple application. Snippet on [gist](https://gist.github.com/Fenex/897403add68729b44dedfb5a2c03147a), screenshot:

![изображение](https://user-images.githubusercontent.com/3790195/75402406-442b8e80-5937-11ea-9680-08976bcb8268.png)

Expected behavior:
1) checkboxes №1 and №2 always must be sync: if №1 is clicked, the application sets the same `selected` value to №2. And vice versa.
2) if checkbox №1 or №2 was clicked, then `selected` property of №3 ckbx must be sets to `true`.

The code compile is ok and application runs good, however checkboxes behavior is pretty strange. First, if I click on the checkbox №1 to select its, neither №2 nor №3 will not selected. Next if I click on a №3, the checkbox is redrawn as selected and immediately comes back to unselected state.

Most exciting is behavior in debug messages is correct. Thus internal state of checkboxex are correct, looks like I need to call additional force redraw function.

What am I doing wrong and how can I change my code to get the expected application behavior?

My original task: possibility changing `selected` status of checkboxes by incoming messages from another thread.

* Windows NT 6.1 (7 SP1)
* stable-x86_64-pc-windows-msvc (default)
* rustc 1.41.0 (5e1a79984 2020-01-27)

**Comment by FloVanGH** [comment]
Should be fixed now, it was an bug in the selection behavior of the CheckBox.

I've also updated the selector api:

You should change:

```rust
.selector(Selector::from("check-box").id("id-1"))
```

to

```rust
.id("id-1")
```

And column 43 should also be:
```rust
   ctx.child("id-1").set("selected", is_selected);
```

**Comment by Fenex** [comment]
Thanks for your answer!

I pulled your changes and now it is look like an unsync between internal & visual states is gone.
