### ISSUE TITLE
TextBox doesn't allow upper-case nor shift+digit (eg !, @, #, ...)

### ISSUE THREAD

**Issue by shadiakiki1986** [redox-os/orbtk#162]
**Describe the bug**
Entering upper-case characters or shift+digit (eg !, @, #, ...) doesn't work

**To Reproduce**
1. `cargo run --example widgets`
2. Type "ABCdef!@#" in the text box
3. See "abcdef123" show up instead

**Expected behavior**
Should see "ABC!@#"

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Additional info:**
From the issue [Text box doesn't filter numbers](https://github.com/redox-os/orbtk/issues/84), I would guess that there is a feature somewhere to filter the input text. Not sure how to disable it or how it gets enabled in the first place. Just guessing though.

**Comment by Kaiden42** [comment]
I noticed the same bug using the german Neo2 as a keyboard layout. It's not possible to type the characters of tier 2 to 6, which need a combination of Shift, Mod3 (Capslock), and Mod4 (Alt Gr) to be typed.

**Desktop:**
Linux Mint 19.3 Cinnamon Edition

**Keyboard layout:**
https://neo-layout.org/

**Comment by FloVanGH** [comment]
!, @, # should work now.

**Comment by mpolosak** [comment]
it still happens to me

**Comment by mpolosak** [comment]
and it doesn't support typing number using numpad

**Comment by kivimango** [comment]
numpad and some other keys missing from the keyboard map, the PR is coming to address this.

**Comment by FloVanGH** [comment]
@kivimango ', /, \, [, ], {, } will be added after my branch is merged. I think this will be done in the next days.
