### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#165]
# Context

The `ProgessBar` should be used to indicates a progress, e.g. the progress by loading a file, or a screen.

# Problem description & Solution

The `ProgressBar` should be indicates the progress between a `min`-value and a `max`-value. The current progress should be set by a `val` property.

# Examples and MockUps

```rust
ProgressBar::create().min(0.0).max(100.0).val(50.0).build(ctx)
```
<img width="365" alt="image" src="https://user-images.githubusercontent.com/6715107/76117713-98e0a080-5fec-11ea-9946-ca57836d1c99.png">

**Comment by kivimango** [comment]
I looked into this and came up with a basic draft, but I stuck since days.
First, I wanted a Container as a child, and modify its width based on _val_, but its an ugly hack, so I started exploring how to draw directly on the canvas based on the canvas example.
My problem is that the RenderPipeline's draw() method gets called only twice at the start of the app, and the value of a Cell<f64> never gets updated (even if I call set() on it in the update() function).
If anyone can help with that, I will happily make a new PR.
Here is the code so far:
https://gist.github.com/kivimango/e674052789818ed3a1fc2df13d61fe54

**Comment by FloVanGH** [comment]
@kivimango the solution with `width` would be fine for me. If you want explicit trigger redraw you could check: https://github.com/redox-os/orbtk/issues/132#issuecomment-571922281

**Comment by kivimango** [comment]
![pgbar_preview1](https://user-images.githubusercontent.com/18540032/80696000-0e418c80-8ad7-11ea-8aca-7e314d271708.jpg)
Here is my work so far, some stuff still needs to be addressed:
I omitted the min and max properties, the caller should do the calculations, the progress bar expects the calculated percent between 0.0 and 1.0 whereas 1.0 = 100%.

- [ ] Setting the background color to black is not working
- [ ] Setting proper paddings (2.0, 2.0, 2.0, 2.0) inside the widget is not working
- [ ] Cannot set the initial width based on _val_ when the widget is initialized: the parent or the widget bounds reported as 0 (it needs the maximum available width to calculate the initial width)
- [ ] Add indeterminate mode: the indicator should roll from left to right and back between the borders when the _val_ is out of range, eg.g <0.0 and >1.0 (how to move a widget ?)

The first two issues maybe can solved by writing a new renderer object, but that would produce duplicate code from the rectangle and text renderer objects.
Contributions are welcome :)

**Comment by lukors** [comment]
Can you post the code?

Regarding paddings and locations: I've used `margin` to set the location of my widgets, don't know if it's the right way, but using the `position` (or whatever it's called) seems to always be overridden by the layout.

**Comment by kivimango** [comment]
yes, I'm committing the changes now, but I don't have time to create a PR.
I will do it when i got home from work tonight.
I tried padding and margin, none of them seems to work (rectangle render object doesnt render a padding as i red the code)

**Comment by kivimango** [comment]
I created a new PR https://github.com/redox-os/orbtk/pull/195, you can view the code.

**Comment by FloVanGH** [comment]
@kivimango at first thank you for your support 🙂.

> Setting the background color to black is not working

There is a global background set on the main theme css file, it overrides all background definitions set on the widgets directly. There we need a better solution. But for now you can define background, border-brush, ... in the `dark.css` for the ProgressBar.

>  Setting proper paddings (2.0, 2.0, 2.0, 2.0) inside the widget is not working

At default widgets are using the default layout object, but if you want to define a padding you need to use the `PaddingLayout` object for the ProgressBar:

```rust
fn layout(&self) -> Box<dyn Layout> {
    Box::new(PaddingLayout::new())
}
```
>  Cannot set the initial width based on val when the widget is initialized: the parent or the widget bounds reported as 0 (it needs the maximum available width to calculate the initial width)

You need to do it in the `update_post_layout` of your state. I will also be called after the ui is created. You could check the slider widget code.

> Add indeterminate mode: the indicator should roll from left to right and back between the borders when the val is out of range, eg.g <0.0 and >1.0 (how to move a widget ?)

That is complicated at the moment, because there is no animation system yet in OrbTk. But it is one of the next points. I would suggest to deliver the indeterminate mode as update after the animation system is ready. What do you think?

**Comment by kivimango** [comment]
Thank you for your answer :)
I was able to set the background to black in the dark.css.I was able to work around the padding issue with setting the margin on the child, and a little hack without using the padding layout in the current state. However, I tried your suggestion, using the layout and padding, but it still doesn't work for me, maybe someone else will be luckier (the bar does not respect the right border).
I fixed the initial width calculation problem by rewriting the logic.

Yes, I agree, with the indeterminate mode can wait (maybe this could be hacked too by moving the child widget to the bounds, and back).

**Comment by FloVanGH** [comment]
@kivimango I’ve tested your implementation and added the PaddingLayout to the ProgressBar widget. You have also to add a padding property of type Thickness to the ProgressBar.

**Comment by FloVanGH** [comment]
@kivimango 

```rust
 ProgressBar<BarState> {
        background: Brush,
        border_brush: Brush,
        border_radius: f64,
        border_width: Thickness,
        padding: Thickness,
        val: f64
    }
);

impl Template for ProgressBar {
    fn template(self, _: Entity, build_context: &mut BuildContext) -> Self {
        self.name("ProgressBar")
            .background("#000000")
            .border_brush("#BABABA")
            .border_radius(4.0)
            .border_width(1.0)
            .element("progress_bar")
            .padding((2.0, 4.0, 4.0, 2.0))
            .height(32.0)
            .child(
                Container::create()
                    .background("#EFD035")
                    .height(24.0)
                    .border_radius(1.0)
                    .width(0.0)
                    .build(build_context),
            )
            .val(0.0)
    }

    fn render_object(&self) -> Box<dyn RenderObject> {
        Box::new(RectangleRenderObject)
    }

   fn layout(&self) -> Box<dyn Layout> {
      Box::new(PaddingLayout::new())
   }
}
```

**Comment by kivimango** [comment]
Done.
