### ISSUE TITLE
Window::create() Cannot find declaration to go to

### ISSUE THREAD

**Issue by maxuanji** [redox-os/orbtk#166]
use orbtk::prelude::*;
fn main() {
    Application::new()
        .window(|ctx| {
            Window::create()    //How to find this declaration 
                .title("OrbTk - minimal example")
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .child(TextBlock::create().text("OrbTk").build(ctx))
                .build(ctx)

        })
        .run();
}

**Comment by FloVanGH** [comment]
The create method of the widgets like window is generated by the `widget!` macro.  Check https://github.com/redox-os/orbtk/blob/abd8f786010584ba21d9f410d381685b14794dad/crates/api/src/macros.rs#L325

**Comment by maxuanji** [comment]
Thank you！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Florian Blasius"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 晚上8:15
收件人: "redox-os/orbtk"<orbtk@noreply.github.com&gt;; 
抄送: "oldma"<1372955781@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [redox-os/orbtk] Window::create() Cannot find declaration to go to (#166)




The create method of the widgets like window is generated by the widget! macro.  Check https://github.com/redox-os/orbtk/blob/abd8f786010584ba21d9f410d381685b14794dad/crates/api/src/macros.rs#L325
