### ISSUE TITLE
How can I specify the position of the widget?

### ISSUE THREAD

**Issue by nabezokodaikon** [redox-os/orbtk#167]
Even if you specify the position function, the position of the widget does not change.
```rust
                .child(
                    ImageWidget::create()
                        .position((300.0, 100.0)) // <- ???
                        .image(img3.clone())
                        .build(ctx),
                )

```

**Comment by FloVanGH** [comment]
The `position` will be calculated internal. There are two ways to overwrite / set the position. First you could set the position if you child is in a absolute layout e.g. the overlay has a absolute layout or you could overwrite the position in the `upate_post_layout` method of the `State`. Alternative you could set margin top and right to position you widget that would work e.g. in a parent Grid.

**Comment by nabezokodaikon** [comment]
I used `update_post_layout` but the application panicked.
What is wrong?

```rust
impl State for MainViewState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {}

    fn update_post_layout(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
        ctx.child("open").set("text", "hello".to_string());
    }
}

widget!(MainView<MainViewState> {
    counter: usize,
    result: String16
});

impl Template for MainView {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.id("mainView").name("MainView").child(
            FontIconBlock::create()
                .child(
                    Button::create()
                        .id("open")
                        // .margin((10.0, 10.0, 0.0, 0.0))
                        .position((100.0, 400.0))
                        .width(100.0)
                        .height(200.0)
                        .text("Open")
```

Error message
```
thread 'main' panicked at 'StringComponentStore.get_mut: internal downcast error', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by FloVanGH** [comment]
`text` is of type `String16`

```rust
ctx.child("open").set("text", String16::from("hello"));
```

should fix it.

**Comment by nabezokodaikon** [comment]
What happens with position?
Panic when executed.
```rust
ctx.child("open").set("position", (100.0, 400.0));
```

**Comment by nabezokodaikon** [comment]
What is the absolute layout method?
This setting did not change.
```rust
ctx.child("open").set("position", Point::new(100.0, 400.0));
```

**Comment by FloVanGH** [comment]
Overlay is only intend to place / draw widgets over the main tree. The layout of the overlay is an absolute layout:

```rust
 fn layout(&self) -> Box<dyn Layout> {
    Box::new(AbsoluteLayout::new())
}
```

With position you should be careful because it could be manipulated internal and it is use in combination of x/y of the bounds property.

For your purpose this should be work:

```rust
Grid::create()
    .child(
        Button::create()
            .id("open")
            // use margin left / top to set the button position in the grid
            .margin((100.0, 400.0, 0.0, 0.0))
            .width(100.0)
            .height(200.0)
            .text("Open")
            .on_click(move |states, _| {
               states.get_mut::<MainViewState>(id).open_dialog();
               true
             })
             .build(ctx),
    )
``` 

But is to absolute position your button really what you need? I would recommend to use it rarely. At the moment the only use of absolute position in OrbTk is it to draw the popup of the combobox on the position of the combobox button, all other stuff I could archive with layouts mechanics (it is more flexible then absolute position).

**Comment by nabezokodaikon** [comment]
So that's it. Revise the way of thinking.
