### ISSUE TITLE
StackLayout uses last child as fixed width/height instead of using the maximum

### ISSUE THREAD

**Issue by valkum** [redox-os/orbtk#168]
**Describe the bug**
See valkum/orbtk-chat#1

**To Reproduce**
1. Add different sized childs to stack
2. The stack has the height/width of the last child in the not growing dimension.

**Expected behavior**
Maybe the biggest child height/width should be used

https://github.com/redox-os/orbtk/blob/abd8f786010584ba21d9f410d381685b14794dad/crates/api/src/layout/stack.rs#L302-L321
```diff
    match orientation {
        Orientation::Horizontal => {
            desired_size.0 += width;
-           desired_size.1 = height;
+           desired_size.1 = desired_size.1.max(height);
        }
        Orientation::Vertical => {
-           desired_size.0 = width;
+           desired_size.0 = desired_size.0.max(width);
            desired_size.1 += height;
        }
```

**Comment by FloVanGH** [comment]
Thank you. That correct the expected behavior is that the biggest height/width should be used. You could create a PR if you want to fix it otherwise I also could do it.
