### ISSUE TITLE
Grid row auto height does not work as expected

### ISSUE THREAD

**Issue by janibonnevier** [redox-os/orbtk#170]
**Describe the bug**
Grid rows with auto height are not sized correctly to contain their children. The children end up overlapping with those of other rows. Unsure whether this issue applies to column width as well.

Thank you for your work on this toolkit. On paper it's exactly what I want. :)

**To Reproduce**
Compile and run the following code.

```rust
use orbtk::prelude::*;

#[derive(Default, AsAny)]
struct MainViewState {}

impl MainViewState {}

impl State for MainViewState {}

widget!(MainView<MainViewState> {
    text: String16
});

impl Template for MainView {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("MainView")
            .width(400.0)
            .height(1000.0)
            .text("")
            .child(
                Grid::create()
                    .rows(
                        Rows::create()
                            .row("auto")
                            .row("auto")
                            .row("auto")
                            .row("auto")
                            .row("auto")
                            .row("auto")
                            .row("auto")
                            .row("auto")
                            .build(),
                    )
                    .child(
                        generate_text_field(ctx, "Title")
                            .attach(Grid::column(0))
                            .attach(Grid::row(0))
                            .build(ctx),
                    )
                    .child(
                        generate_text_array_field(ctx, "Authors")
                            .attach(Grid::column(0))
                            .attach(Grid::row(1))
                            .build(ctx),
                    )
                    .child(
                        generate_text_array_field(ctx, "Owners")
                            .attach(Grid::column(0))
                            .attach(Grid::row(2))
                            .build(ctx),
                    )
                    .child(
                        generate_text_array_field(ctx, "Recipients")
                            .attach(Grid::column(0))
                            .attach(Grid::row(3))
                            .build(ctx),
                    )
                    .child(
                        generate_text_field(ctx, "Type")
                            .attach(Grid::column(0))
                            .attach(Grid::row(4))
                            .build(ctx),
                    )
                    .child(
                        generate_text_array_field(ctx, "Languages")
                            .attach(Grid::column(0))
                            .attach(Grid::row(5))
                            .build(ctx),
                    )
                    .child(
                        generate_text_array_field(ctx, "Tags")
                            .attach(Grid::column(0))
                            .attach(Grid::row(6))
                            .build(ctx),
                    )
                    .child(
                        generate_text_array_field(ctx, "Keywords")
                            .attach(Grid::column(0))
                            .attach(Grid::row(7))
                            .build(ctx),
                    )
                    .build(ctx),
            )
    }
}

fn generate_text_field(ctx: &mut BuildContext, label: &str) -> Container {
    Container::create()
        .padding(8)
        .border_width(2.0)
        .border_brush(Color::rgb(255, 255, 255))
        .child(
            Grid::create()
                .rows(Rows::create().row("auto").row("auto").build())
                .child(
                    orbtk::TextBlock::create()
                        .attach(Grid::row(0))
                        .text(label)
                        .build(ctx),
                )
                .child(
                    orbtk::TextBox::create()
                        .attach(Grid::row(1))
                        .width(300.0)
                        .text("")
                        .build(ctx),
                )
                .build(ctx),
        )
}

fn generate_text_array_field(ctx: &mut BuildContext, label: &str) -> Container {
    Container::create()
        .padding(8)
        .border_width(2.0)
        .border_brush(Color::rgb(255, 255, 255))
        .child(
            Grid::create()
                .columns(Columns::create().column("auto").column("auto").build())
                .rows(Rows::create().row("auto").row("auto").row("auto").build())
                .child(
                    TextBlock::create()
                        .attach(Grid::row(0))
                        .text(label)
                        .build(ctx),
                )
                .child(
                    TextBox::create()
                        .width(300.0)
                        .text("")
                        .attach(Grid::column(0))
                        .attach(Grid::row(1))
                        .build(ctx),
                )
                .child(
                    Button::create()
                        .size(40.0, 32.0)
                        .text("Delete")
                        .attach(Grid::row(1))
                        .attach(Grid::column(1))
                        .build(ctx),
                )
                .child(
                    Button::create()
                        .size(40.0, 32.0)
                        .text("Add")
                        .attach(Grid::row(2))
                        .attach(Grid::column(0))
                        .build(ctx),
                )
                .build(ctx),
        )
}

pub fn main() {
    orbtk::Application::new()
        .window(|ctx| {
            Window::create()
                .title("Window Title")
                .position((100.0, 100.0))
                .resizeable(true)
                .size(450.0, 500.0)
                .child(MainView::create().build(ctx))
                .build(ctx)
        })
        .run();
}
```

**Expected behavior**
The rows should automatically be made tall enough to fully contain their respective children. The same should be true for the width of columns with auto width.

**Screenshots**
![Screenshot_2020-03-10_22-12-28](https://user-images.githubusercontent.com/6655449/76359930-47058680-631c-11ea-8c1a-93ac2e4233ed.png)

**Desktop**
- OS: Arch Linux with XFCE 4.14

**Additional context**
OrbTk rev abd8f786010584ba21d9f410d381685b14794dad (current `develop`)

**Comment by FloVanGH** [comment]
Until it is fixed as workaround you could set fixed height instead of auto. If the height or width is fixed and know I would suggest to use fixed values instead of auto also in general, because it reduces the calculation in the layout.  

But we have to the `auto` calculation, thank you for the report and the example 🙂.

**Comment by kivimango** [comment]
i started looking into this.
I added some println to the calculate_row_weight() fn in [grid.rs](https://github.com/redox-os/orbtk/blob/develop/crates/api/src/layout/grid.rs)

```rust
    if row.height != RowHeight::Auto {
            return;
        }

        println!("0: begin calculating rows, row number: {}", grid_row);

        let child_height = self.children_sizes.borrow().get(&child).unwrap().1;

        println!("1: child_height: {}", child_height);

        if let Some(height) = row_heights.get(&grid_row) {
            println!("2A: height: {}", height);
            if *height < child_height + margin.top() + margin.bottom() {
                let s = child_height + child_height + margin.top() + margin.bottom();
                println!("2B: height is smaller than child height + margins, inserting new height {} for row {}", s, grid_row);
                row_heights.insert(grid_row, s);
            }
        } else {
            row_heights.insert(grid_row, child_height + margin.top() + margin.bottom());
            println!("3: height is not in the BTreeMap, inserting height {} for row {}", child_height + margin.top() + margin.bottom(), grid_row);
        }
```

Running the example provided produces the following:
0: begin calculating rows, row number: 0
1: child_height: 16
3: height is not in the BTreeMap, inserting height 16 for row 0
0: begin calculating rows, row number: 1
1: child_height: 32
3: height is not in the BTreeMap, inserting height 32 for row 1
0: begin calculating rows, row number: 1
1: child_height: 36
2A: height: 32
2B: height is smaller than child height + margins, inserting new height 72 for row 1
0: begin calculating rows, row number: 2
1: child_height: 36
3: height is not in the BTreeMap, inserting height 36 for row 2

Seems like calculation is OK, the inserted heights in the BtreeMap somehow are overwritten repeatedly.

**Comment by FloVanGH** [comment]
Ok thank you for help. Do you want to fix it? Otherwise I can do it.

**Comment by kivimango** [comment]
Yes, I would like to, but im not so familiar with this part of the codebase.
Can you give me some direction ?
Thanks.

**Comment by FloVanGH** [comment]
Do you have a concrete question. Would do you need to know to start?

**Comment by kivimango** [comment]
Yes, I would like to know where to start.
How does the GridLayout exactly work?

**Comment by FloVanGH** [comment]
Ok will try it.

common layouting:

* `measure`: ask every child which is it's favorite size
* `arrange`: calculate real size and sets the position of the children

grid layouting:

* The grid is inspired by the Grid control of WPF https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.grid?view=netcore-3.1
* Fixed size of a column or row `Grid::columns(Columns::create().column(16)`: The column or row has a fixed width / height independent from size of children
* Stretch size of a column or row `Grid::columns(Columns::create().column("*")`: The column or row uses the remaining space, multiple stretch columns or row are possible. If there are multiple stretch columns or rows, they share the rest remaining space to equal parts
* Auto size of a column or row `Grid::columns(Columns::create().column("auto")`: The column or row gets the width / height of the widest or highest children in the row or column.

I hope this is enough to start, otherwise let me know

**Comment by kivimango** [comment]
Sorry, I will have to pass on this. I cannot set up a proper debugger on win 10, and in my linux vm VS Code constantly crashing.

**Comment by FloVanGH** [comment]
Do you have tried the Code LLDB plugin for vs code. That works for me on windows. You can use it also in combination with the rust-analyzer plugin.

**Comment by kivimango** [comment]
Oh, I see now. Thanks.

**Comment by kivimango** [comment]
I changed the code on line 283 from
```rust
desired_size.1 = desired_size.1.max(child_desired_size.height());
```
to
```rust
desired_size.1 += desired_size.1.max(child_desired_size.height());
```
and now this looks like:

![grid_prev](https://user-images.githubusercontent.com/18540032/93455540-c46a0f00-f8dc-11ea-88c4-eaf4a6678afd.jpg)

but this not solves the problem, because if a row has 3 children layed out in a row, next to each other, the height will be the sum of the 3 children's heights, instead of the tallest.

I think the problem is the logic does not care about the alignment of the children, like when
all children placed next to each other in a row, ot they are placed on top of each other, like a stack.

**Comment by arctic-alpaca** [comment]
I created a PR #360 based on what @kivimango already found out, I hope this fixes the problem at least for grid in grid layouts.
