### ISSUE TITLE
Minimal Window panics while resizing

### ISSUE THREAD

**Issue by Gaarco** [redox-os/orbtk#182]
When I launch a sample resizeable window it panics every time while resizing:
render 33ms - timer ended
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UpdateFailed("Update failed because input buffer is too small. Required size for 450 x 731 window (1x scale) is 1315800 bytes but the size of the input buffer has the size 1229320 bytes")', /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/orbtk-shell-0.3.0-alpha1/src/minifb/mod.rs:251:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 - Manjaro GNU/Linux
 - Orbtk version: 0.3.1alpha1

**Backtrace:**
    RUST_BACKTRACE=full cargo run
     Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/pomodoro`
render 51ms - timer ended
render 32ms - timer ended
render 1ms - timer ended
render 1ms - timer ended
render 34ms - timer ended
render 34ms - timer ended
render 33ms - timer ended
render 2ms - timer ended
render 1ms - timer ended
render 2ms - timer ended
render 1ms - timer ended
render 1ms - timer ended
render 48ms - timer ended
render 1ms - timer ended
render 17ms - timer ended
render 1ms - timer ended
render 1ms - timer ended
render 16ms - timer ended
render 1ms - timer ended
render 1ms - timer ended
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UpdateFailed("Update failed because input buffer is too small. Required size for 393 x 723 window (1x scale) is 1136556 bytes but the size of the input buffer has the size 1136296 bytes")', /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/orbtk-shell-0.3.0-alpha1/src/minifb/mod.rs:251:13
stack backtrace:
   0:     0x55b45b53c8c4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55b45b53c8c4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55b45b53c8c4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55b45b53c8c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b45b55929c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55b45b53a737 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55b45b53ea65 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b45b53ea65 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b45b53ea65 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55b45b53e751 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55b45b53f0ca - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55b45b53ecb0 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55b45b557de1 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55b45b557c03 - core::option::expect_none_failed::he6711468044f7162
                               at src/libcore/option.rs:1199
  14:     0x55b45b32ea91 - core::result::Result<T,E>::unwrap::h9406308d8e2fd503
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:963
  15:     0x55b45b314caf - orbtk_shell::platform::WindowShell<A>::flip::hf42b0acac25d436a
                               at /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/orbtk-shell-0.3.0-alpha1/src/minifb/mod.rs:251
  16:     0x55b45b314130 - orbtk_shell::platform::ShellRunner<A>::run::haf16e4ef2e42010c
                               at /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/orbtk-shell-0.3.0-alpha1/src/minifb/mod.rs:309
  17:     0x55b45b36e783 - orbtk_api::application::Application::run::h8f37c74fad956e73
                               at /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/orbtk-api-0.3.0-alpha1/src/application/mod.rs:219
  18:     0x55b45b2a4019 - pomodoro::main::h4a6e50be155ca9d5
                               at src/main.rs:4
  19:     0x55b45b28fbc0 - std::rt::lang_start::{{closure}}::h2bfd663373b8ba68
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  20:     0x55b45b53eb93 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  21:     0x55b45b53eb93 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  22:     0x55b45b541567 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  23:     0x55b45b53f570 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  24:     0x55b45b53f570 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  25:     0x55b45b53f570 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  26:     0x55b45b28fb99 - std::rt::lang_start::h2b84bd4419fb7993
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  27:     0x55b45b2a404a - main
  28:     0x7f1df3f4f023 - __libc_start_main
  29:     0x55b45b28a15e - _start
  30:                0x0 - <unknown>

**Comment by FloVanGH** [comment]
Unfortunately there is a resizing bug with 0.3.1alpha1. The next release will fix it. In the meantime you could reference the develop branch `orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }

**Comment by FloVanGH** [comment]
The bug is fixed in 0.3.1-alpha2
