### ISSUE TITLE
Text input drops characters

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#187]
**Describe the bug**
When writing in a text field, some button presses are ignored when you write too fast.

**To Reproduce**
1. Run Widget Template
2. Click in a text box
3. Mash keyboard (preferably keyboard has n-key rollover)
4. See that not all pressed keys are included.

**Expected behavior**
All button presses should register.

**Desktop:**
 - OS: Windows 10

**Comment by FloVanGH** [comment]
Thank you for the report. At next I will work on some performance improvements. On this I will check also this bug.

**Comment by kivimango** [comment]
This is probably related to #179

**Comment by lukors** [comment]
> This is probably related to #179

Could be. But usually programs are able to capture all input even if they have really low frame rate.

**Comment by FloVanGH** [comment]
should be fixed.
