### ISSUE TITLE
Is it possible to make a node editing GUI?

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#188]
Is it currently possible to make a node editing gui in OrbTK? Something similar to what's seen in Blender: https://duckduckgo.com/?t=ffab&q=blender+node&iax=images&ia=images

I realize some features that would be nice like drag and drop aren't in yet. But I can probably work around things like that if I just know it's possible to render an arbitrary number of widgets somehow.

**Current situation**
I'm trying to render an arbitrary number of widgets, but I can't find any example code that shows this and haven't been able to figure it out on my own.

I saw the `List` in the `widgets` example, but they seem to render a pre-determined list of `String`s, which is not what I want. When I tried a similar thing I ran into the issue of `IntoPropertySource` not being implemented for `Vec<MyStruct>>`. Can't figure out how to `impl` that.

Any pointers are appreciated!

**Comment by kivimango** [comment]
Not sure what it does exactly, but there is a macro called into_property_source!() in crates\api\src\macros.rs,
You can try wrapping the properties of your widgets in the macro.
Also, you can modify your widget's children at runtime, but there is no documentation for that yet.
Look into the last comments on https://github.com/redox-os/orbtk/issues/183.

**Comment by FloVanGH** [comment]
@lukors I think it would possible to develop a node editing GUI with OrbTk. Drag and drop is not yet implemented but it would be possible to implement a custom drag and drop for the nodes. You could check the `ListView` widget. It creates a dynamic number of widgets and uses a builder `Fn` to define the generat children. It should be possible to do it similar for the nodes.

**Comment by lukors** [comment]
After many hours of tiny experiments I'm slowly starting to understand how this works, I think. There are still a ton of things left to do, but I feel like I have some basic understanding now.

Look what I have:

![2020-04-23_20-21-55](https://user-images.githubusercontent.com/1719884/80135278-4e1ce700-85a0-11ea-8023-7c8f071c9a2f.gif)

Thanks to both of you for your critical help!
