### ISSUE TITLE
Circle + `border_brush` + `border_width` = rendering bug

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#189]
**Describe the bug**
A `Container` that is rendered as a circle due to a high `border_radius` receives an extra line drawn over it if the `border_brush` and `border_width` properties are set.

**To Reproduce**
Here is some code to reproduce, it's the same code used when creating the screenshot:

```rust
use orbtk::prelude::*;

const CIRCLE_SIZE: f64 = 200.;

fn main() {
    Application::new()
        .window(|ctx| {
            Window::create()
                .position((100.0, 100.0))
                .size(220.0, 220.0)
                .child(
                    Container::create()
                        .width(CIRCLE_SIZE)
                        .height(CIRCLE_SIZE)
                        .border_radius(CIRCLE_SIZE * 0.5)
                        .border_brush(Brush::SolidColor(Color::rgb(200, 200, 200)))
                        .border_width(3.)
                        .build(ctx))
                .build(ctx)
        })
        .run();
}
```

From what I can find, the properties that are required to reproduce the bug are `border_brush` and `border_width`. If any of those two are removed the bug is gone.

**Expected behavior**
The extra line seen in the screenshot should not be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/1719884/80290283-a42a8f80-8744-11ea-9848-b95f80b24512.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by FloVanGH** [comment]
done!
