### ISSUE TITLE
Change when `on_mouse_up` closure is called

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#190]
# Context
The feature will be used when a developer wants to call a function on a widget when a mouse button is released while hovering it.

# Problem description
I'm using the `on_mouse_down` closure in `MouseHandler` to know when the user has pressed the mouse on a widget, I use that to tell a handler widget that "this is now being dragged-and-dropped". Then the user drags the mouse and lets go of the mouse on another widget, this tells the handler widget that "it was dropped on this widget".

Currently to achieve the "release" behavior I'm using `on_mouse_up_global`. This calls a function on every widget that has it any time the user lets go of their mouse button. However, this is wasteful as I then have to calculate if the mouse is over the widget. What I actually want—and what I expected `on_mouse_up` to do—is to call a closure only on the widget the mouse is released on.

# Solution
I would suggest changing `on_mouse_up` to work as I expected (to be called whenever the mouse is released when hovering a widget), because it then mirrors the functionality of `on_mouse_down`, like its name suggests.

The current functionality of `on_mouse_up` could be renamed to something like `on_mouse_up_sticky`, to clearly show that this is a "sticky" mode that will call on the widget it was pressed on once the button is released.

# Examples and MockUps
Here is an example of how I imagine it working:
```rust
self.name("MyWidgetView")
    .width(50.)
    .height(50.)
    // This closure is called when the mouse button is released
    // while hovering the widget:
    .on_mouse_up(move |states, p| {
        states
            .get_mut::<SlotState>(id)
            .mouse_action(MouseAction::MouseReleased, _);
    })
    // This closure is called when the mouse button is released after
    // first being pressed while hovering the widget:
    .on_mouse_up_sticky(move |states, p| {
        states
            .get_mut::<SlotState>(id)
            .mouse_action(MouseAction::MouseReleasedSticky, _);
    })
    .child(MouseBehavior::create().enabled(id).target(id.0).build(ctx))
```

**Comment by FloVanGH** [comment]
@lukors I would suggest to only have one `mouse_up` callback and to remove only the restriction that the element must be pressed before.

**Comment by FloVanGH** [comment]
Done.
