### ISSUE TITLE
How to best handle inputs?

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#192]
I would like to check if the way I'm handling my inputs makes sense or if there is a better way.

In this example I want to call a function in `MyContainerView` when its child `MyWidgetView` is clicked. I want to send the `MyWidgetView`'s `Entity` as a parameter to the function.

# This is how I do it
This is pseudo-code. First, these are the `struct`s:

```rust
widget!(
    MyContainerView<MyContainerState> {
        entity_clicked: Option<Entity>
    }
)

struct MyContainerState {}

widget!(
    MyWidgetView<MyWidgetState>: MouseHandler {
        container_entity: Entity
    }
)

struct MyWidgetState {
    clicked: bool
}
``` 

1. When `MyWidgetView` is created I send the `Entity` of `MyContainerView` with it to be stored in `MyWidgetView.container_entity`.
3. In `MyWidgetView` I use `on_mouse_click` to call `MyWidgetState.widget_clicked()`.
4. `MyWidgetState.widget_clicked()` sets `self.clicked = true`.
5. In `MyWidgetState.update()` I check if `self.clicked`, and if it is I set `MyContainerView.entity_clicked` to `MyWidgetView.Entity`. Then I reset `self.clicked` to `false`.
6. In `MyContainerState.update()` I check what `entity_clicked` is set to, and if it's set to something I call `MyContainerState.function_i_want_to_call()` with the `Entity` in `MyContainerView.entity_clicked` as parameter, then reset `MyContainerView.entity_clicked` to `None`.

So that's how I do it. Can it be improved?

# Order of execution?
An issue I have with this way is that there is a 1 frame delay between the click and it being registered because of the following order of execution, correct me if I'm wrong:

1. The click is registered
1. `MyContainerState.update()` is called
2. `MyWidgetState.update()` is called <- It sets the variable in `MyContainerView`
3. The UI is drawn <- I can not see the effects of my click in this frame
4. `MyContainerState.update()` is called <- It runs the function based on the click
5. The UI is drawn <- Now I can see the effects

It would be good if I could handle the input in a separate `update()` loop before the "real" update loop to ensure that it has all the inputs, but I can't find any such function. How can I get around this?

**Comment by kivimango** [comment]
can you try please moving your logic into the impl State's _update_post_layout()_ function from _update()_?
According to docs:

> This update method is called after layout is calculated and before rendering.

**Comment by lukors** [comment]
I made a minimal example and tried doing that, but it doesn't seem to make any difference in this case.

The problem for me is that it still isn't done before the `update()` method somehow. Look at this minimal example that you can test:

```rust
use orbtk::{prelude::*, behaviors::MouseBehavior};

fn main() {
    Application::new()
        .window(|ctx| {
            Window::create()
                .position((100.0, 100.0))
                .size(300.0, 300.0)
                .child(MyContainerView::create().build(ctx))
                .build(ctx)
        })
        .run();
}

#[derive(Default, AsAny)]
pub struct MyContainerState {
    clicked: bool
}

type OptionEntity = Option<Entity>;

widget!(
    MyContainerView<MyContainerState>: MouseHandler {
        entity_clicked: OptionEntity
    }
);

impl Template for MyContainerView {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("MyContainerView")
            .id("container")
            .on_click(move |states, _| {
                states
                    .get_mut::<MyContainerState>(id)
                    .container_clicked();
                false
            })
            .child(
                MouseBehavior::create()
                    .enabled(id)
                    .target(id.0)
                    .build(ctx)
            )
            .child(
                MyWidgetView::create()
                .build(ctx)
            )
    }
}

impl State for MyContainerState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {

        let clicked_entity = *ctx.widget().get::<OptionEntity>("entity_clicked");
        if clicked_entity.is_some() {
            println!("Container update: Got entity: {:?}", clicked_entity.unwrap());
            ctx.widget().set::<OptionEntity>("entity_clicked", None);
        } else {
            println!("Container update: Nothing yet..");
        }

        if self.clicked {
            println!("Container update: I just got clicked");
            self.clicked = false;
        }
    }
}

impl MyContainerState {
    fn container_clicked(&mut self) {
        self.clicked = true;
    }
}


#[derive(Default, AsAny)]
pub struct MyWidgetState {
    clicked: bool,
}

widget!(
    MyWidgetView<MyWidgetState>: MouseHandler {
        container_entity: Entity
    }
);

impl Template for MyWidgetView {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("MyWidgetView")
            .width(200.)
            .height(200.)
            .on_click(move |states, _| {
                states
                    .get_mut::<MyWidgetState>(id)
                    .widget_clicked();
                false
            })
            .child(
                MouseBehavior::create()
                    .enabled(id)
                    .target(id.0)
                    .build(ctx)
            )
            .child(
                Container::create()
                .background(Color::rgb(0, 150, 0))
                .build(ctx)
            )
    }
}

impl State for MyWidgetState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
    }

    fn update_post_layout(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {

        if self.clicked {
            let entity = ctx.widget().entity();
            ctx.parent_from_id("container").set::<OptionEntity>("entity_clicked", Some(entity));
            self.clicked = false;
            println!("Widget post_layout_update: I just got clicked");
        }
    }
}

impl MyWidgetState {
    fn widget_clicked(&mut self) {
        self.clicked = true;
    }
}
```

The output for me is the following:
```
[...]
Container update: Nothing yet..
Container update: I just got clicked
Widget post_layout_update: I just got clicked
Container update: Got entity: Entity(3)
```
This shows clearly that the Container's `update()` function knows that it has been clicked before the Widget's `update_post_layout()` function.

It doesn't matter if I use the `update()` or `update_post_layout()` functions in the Widget, the order is the same.

If `update_post_layout()` actually happens before `update()`, it should look like this:
```
[...]
Container update: Nothing yet..
Widget post_layout_update: I just got clicked
Container update: Got entity: Entity(3)
Container update: I just got clicked
```

The current order isn't necessarily wrong, but I'm confused over what the actual order is, because that decides how I make my program. I had assumed that `update_post_layout()` ran before `update()`, but if it doesn't I have to work around the fact that I can't handle my inputs in a separate step before the `update()` loop. And even worse—I have to live with a 1 frame delay in my input!

So that's why I'm wondering if my approach makes sense, maybe I'm doing something fundamentally wrong? Does anyone know the actual order of the operations? I've tried looking in the code, but I can't figure it out.

I've thought about handling all input in the `Container`, so that when you click in it, it creates bounding boxes for all its children and checks if you hit any of them. That seems redundant though because the clicking stuff in OrbTk already does that, probably in an optimized way, so having to manually re-implement the same thing seems wasteful.

**Comment by lukors** [comment]
I've looked into this some more, doing experiments with trying to send the id of the target widget the click should affect straight to the child's `MouseBehavior`, and trying out shared properties. From my understanding there is always at least a one frame delay if you want to "send clicks" up the tree.

I realized that `MouseBehavior` is also just a widget. One which is convenient to use when you want to have clickable things, because it handles some parts in a convenient way and sends events to its parent when it's clicked.

However, it sends this event in its update loop. Since it seems like the update loops are ran from topmost parent and down towards leafs, this means that the parent won't get the event until the next update loop, after one drawn frame. So in my example there are actually two frame delays, as first the `MouseBehavior`'s update loop is ran, which sends an event to its parent `MyWidgetView`, which in its update loop sets a value in its parent `MyContainerView`, which in its update loop uses the value to call a function.

The only way I can see to get around this is to get the clicking information right in the update loop for `MyContainerState` (which is now done in `MouseBehavior`), and loop through all its children's bounding boxes to see which ones get hit.

This would be the fastest possible I can think of, but then of course I don't know when the click events are gathered. However since it's done in the update loop in `MouseBehavior`, I'm assuming that the update loop is the earliest place you can access the data, so probably click events are gathered before the update loop.

Is a solution for zero-frame-delay input not implemented yet, or am I missing something?

---
By the way, shared properties are pretty cool, but unfortunately doesn't speed anything up since you still need to set the shared property in an update loop, which is of course no faster than just setting a property straight on the parent in that same update loop.

**Comment by lukors** [comment]
I've implemented what seems like the fastest way to get inputs as an example.

The idea is to grab the click events in the same way as the `MouseBehavior` does, but instead of then sending an event to the parent (like `MouseBehavior` does)—which results in that event being seen by the parent in the next update loop—it sends the click event (including the location of the click) down to its children.

This means that in the same update loop as the click gets registered, the children will know they got clicked, and can manually check if any of *their* children were clicked by comparing their bounds to the click location, and act according to that.

I've got some code below, it's got a `Workspace` with a child `NodeContainer` with a couple of children `Container`s to represent nodes.

The output I get from the code is the following:
```
Workspace update: got clicked, sending event
Workspace update: finished
NodeContainer update: got click event: Press(Point { x: 45.0, y: 38.0 })
Clicked child: Entity(3)
NodeContainer update: finished
```
Looks like I want it to. :)

Here's the code:
```rust
use orbtk::prelude::*;
use std::cell::Cell;

fn main() {
    // use this only if you want to run it as web application.
    orbtk::initialize();

    Application::new()
        .window(|ctx| {
            Window::create()
                .title("Low latency test")
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .child(Workspace::create().build(ctx))
                .build(ctx)
        })
        .run();
}

widget!(Workspace<WorkspaceState>: MouseHandler {
});

impl Template for Workspace {
    fn template(mut self, id: Entity, ctx: &mut BuildContext) -> Self {
        let node_container = NodeContainer::create().build(ctx);
        self.state_mut().node_container = node_container.into();

        self.name("Workspace")
            .on_mouse_down(move |states, p| {
                states
                    .get::<WorkspaceState>(id)
                    .action(Action::Press(p));
                false
            })
            .child(node_container)
    }
}

#[derive(Default, AsAny)]
struct WorkspaceState {
    action: Cell<OptionAction>,
    node_container: Entity,
}

impl State for WorkspaceState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
        let option_action = self.action.get();
        if let Some(action) = option_action {
            match action {
                Action::Press(p) => {
                    if check_mouse_condition(p, &ctx.widget()) {
                        println!("Workspace update: got clicked, sending event");
                        ctx.get_widget(self.node_container).set::<OptionAction>("action", option_action);
                    }
                }
                _ => {}
            }
            self.action.set(None);
        }
        println!("Workspace update: finished");
    }
}

impl WorkspaceState {
    fn action(&self, action: Action) {
        self.action.set(Some(action));
    }
}



type OptionAction = Option<Action>;
widget!(NodeContainer<NodeContainerState> {
    action: OptionAction
});

impl Template for NodeContainer {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        let child_a = Container::create()
            .width(100.)
            .height(100.)
            .background(Brush::SolidColor(Color::rgb(0, 255, 0)))
            .build(ctx);

        let child_b = Container::create()
            .width(100.)
            .height(100.)
            .margin(Thickness {
                left: 200.,
                right: 0.,
                top: 0.,
                bottom: 0.,
            })
            .background(Brush::SolidColor(Color::rgb(0, 255, 0)))
            .build(ctx);

        self.name("NodeContainer")
            .child(child_a)
            .child(child_b)
    }
}

#[derive(Default, AsAny)]
struct NodeContainerState {}

impl State for NodeContainerState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
        if let Some(action) = *ctx.widget().get::<OptionAction>("action") {
            println!("NodeContainer update: got click event: {:?}", action);

            match action {
                Action::Press(p) => {
                    for child in get_children(ctx) {
                        if ctx.get_widget(child).get::<Rectangle>("bounds").contains((p.x, p.y)) {
                            println!("Clicked child: {:?}", child);
                        }
                    }
                }
                _ => {}
            };

            ctx.widget().set::<OptionAction>("action", None);
        }

        println!("NodeContainer update: finished");
    }
}

fn get_children(ctx: &mut Context) -> Vec<Entity> {
    let mut output: Vec<Entity> = Vec::new();

    for i in 0.. {
        if let Some(child) = ctx.try_child_from_index(i) {
            output.push(child.entity());
        } else {
            break
        }
    }

    output
}

#[derive(Debug, Copy, Clone)]
enum Action {
    Press(Point),
    Release(Point),
    Scroll(Point),
}
```

I'm still looking for information about if this is the proper way, or if there's a better way, or maybe a better way planned? Or should I make an issue to plan a better way?

**Comment by FloVanGH** [comment]
@lukors nice work.

Sorry for the delayed response. 

I think at the moment your solution is the proper way. But I'm not entirely happy with the process of events and states calls. That is one point I want definitely to refactor. For the next I will also implement some mechanics that make it easier to start async tasks from a state and receives their results. I think this will be a good point to refactor the state and event stuff. But before that I will work on a better OrbTk performance.

**Comment by lukors** [comment]
Thanks a lot for the response!

Good to know I'm doing it the proper way, and thank you for the information, I like the future plans and their priority.

---
I was hoping that implementing this fastest way to get inputs I would see a measurable improvement in input lag in my application. Unfortunately its seems to be about the same. But at least I receive all inputs at the same time now, so I don't need to save the previous frame's inputs!

So I think that marks the end of this issue as I now know the currently best way and how it will be improved. Closing the issue.
