### ISSUE TITLE
Help getting keyboard input

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#196]
I'm trying to get keyboard input, but I can't figure it out.

I'm looking at the [`text_box` widget](https://github.com/redox-os/orbtk/blob/develop/crates/widgets/src/text_box.rs) as reference.

I expect the following code to print `key_down` when I press a button, but it doesn't print anything, what am I missing?

```rust
use orbtk::prelude::*;

fn main() {
    Application::new()
        .window(|ctx| {
            Window::create()
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .child(MyWidget::create().build(ctx))
                .build(ctx)
        })
        .run();
}


widget!(MyWidget<MyWidgetState>: KeyDownHandler {});

impl Template for MyWidget {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("MyWidget")
            .on_key_down(move |states, event| -> bool {
                println!("key_down");
                false
            })
    }
}

#[derive(Default, AsAny)]
struct MyWidgetState {}
impl State for MyWidgetState {}
```

**Comment by FloVanGH** [comment]
The element need to be focused to get key events. Therefore it need a `focused` property https://github.com/redox-os/orbtk/blob/928a4c1f39de7ed158d7a0feb1ef5b16bdc40ce5/crates/widgets/src/text_box.rs#L358. And you need to request the focus https://github.com/redox-os/orbtk/blob/928a4c1f39de7ed158d7a0feb1ef5b16bdc40ce5/crates/widgets/src/text_box.rs#L86. You could request focus also on init. 

I think about to add also global key events that not depends on focus.

**Comment by lukors** [comment]
Ah yeah, that makes sense, and it works.

I think having a global key event also is a good idea.

Thank you! :)
