### ISSUE TITLE
New widget: PasswordInput

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#197]
# Context
When users need to enter their password, there is no dedicated widget for this use case.
The TextBox widget displays the password, which is sensitive data.

# Problem description & Solution
Create a new widget that displays an echo character instead of the entered text.
For security reasons, the variable holding the password should be zeroed or dropped after the caller checked against the entered password (maybe even the memory area holding the password could be encrypted somehow)

# Examples and MockUps
`PasswordInput::create().build(ctx)`

![pwinput_preview1](https://user-images.githubusercontent.com/18540032/80920305-34815980-8d6f-11ea-95c9-7959b449bd7e.jpg)

**Comment by FloVanGH** [comment]
The password input could be implemented as extension of the TextBox.

e.g.
```Rust
TextBox::create().mask('*').is_password(true)
```

**Comment by kivimango** [comment]
I think modifying the current code of TextBox is a bad idea (it adds one or more responsibility).
The new widget would be just a wrapper on top of TextBox, only it should mask the input text only, otherwise, it would just call the children TextBox.
Or extract the common functionality into a separate widget/behavior, like BaseInput. and use the extracted behavior in the two widgets.

**Comment by FloVanGH** [comment]
My intention to reduce duplicated code. I was not sure if there is a good way to wrap the TextBox in a PasswordBox, because it has only a text property that is used to display the text and is changed instant by text input. Therefore my idea was to introduce a display_text property, that is only that what is displayed. 
I like your idea to extract the text input behavior, that could be a good solution l, also for other new text input widgets 🙂.

**Comment by kivimango** [comment]
I'm thinking of moving the current logic of TextBox into a separate widget/behavior which manipulates the parent text property, and in TextBox just make it as a child and add 
`.editor(TextEditor::create())`.
Thus we can share the same functionality across different widgets.
Users can implement their own editors.
Adding new text related widgets should be easy as one two three.
I will play around with this and make a PR.

**Comment by rzerres** [comment]
@kivimango any progress with your playground?
I would like to use this, too!

**Comment by kivimango** [comment]
> @kivimango any progress with your playground?
Not yet, I'm currently writing my own app, but I would like to make it in the next few days (maybe a week).
I will let you know here or on the chat, or you can check the pull requests frequently.

**Comment by rzerres** [comment]
> > @kivimango 
> ... but I would like to make it in the next few days (maybe a week).

I will work on my code and will postpone the login dialog until i can implement it with this upcoming widget.
Maybe this can be wrapped with an overlay, combined with an image (roughly mimic the OS-default login windows?)
