### ISSUE TITLE
Crash when deleting `ComboBox` in `update()` or `update_post_layout()`

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#201]
**Describe the bug**
If you delete a `ComboBox` in the `update()` or `update_post_layout()` loop, the program crashes soon after.

**To Reproduce**
Run this code:

```rust
use orbtk::prelude::*;

fn main() {
    Application::new()
        .window(|ctx| {
            Window::create()
                .title("Crash bug example")
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .child(MyWidget::create().build(ctx))
                .build(ctx)
        })
        .run();
}

widget!(
    MyWidget<MyWidgetState> {}
);

impl Template for MyWidget {
    fn template(self, _id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("MyWidget").child(ComboBox::create().build(ctx))
    }
}

#[derive(Default, AsAny)]
pub struct MyWidgetState {}

impl State for MyWidgetState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context) {
        ctx.clear_children();
    }

    fn update_post_layout(&mut self, _: &mut Registry, ctx: &mut Context) {
        ctx.clear_children();
    }
}
```

Produces the following error message:
```
thread 'main' panicked at 'Entity 13 does not contain property type TypeId { t: 9785122672296426403 } with key: open', <::std::macros::panic macros>:5:6
```

**Expected behavior**
It should not crash.

**Desktop**
 - OS: Windows 10

**Additional context**
Note that this does not seem to happen when deleting the `ComboBox` in `init()`.

**Comment by lukors** [comment]
I tested every other widget, and none of the others crash from this. :)

**Comment by FloVanGH** [comment]
Thank you I'll check it.

**Comment by FloVanGH** [comment]
It is fixed now. The problem was, that the Popup of the ComboBox is not a child of the ComboBox. It is a child of Overlay. Therefore the Popup was not removed and tried to access properties of the ComboBox. The Popup will now also removed if the ComboBox is removed.
