### ISSUE TITLE
Can't click to place caret in `TextBox`

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#204]
**Describe the bug**
If you select a `TextBox` with some text in it, all the text in the box will be selected. Clicking again on the text does not deselect the text and place the caret in the clicked location.

**To Reproduce**
1. Run widgets example
2. Write some text in one of the text boxes
3. Click outside the text box to deselect it
4. Click on the text to select it
5. Click on the text again

The text is still selected, the caret is not moved.

**Expected behavior**
The caret should be placed where you click the second time, and the text should deselect.

**Desktop**
 - OS: Windows 10

**Comment by FloVanGH** [comment]
Unfortunately this is not implement now. But this is a good task to start next.

**Comment by andreinbio** [comment]
Hello @FloVanGH ,
I was trying to implement this functionality but I encountered a block.
My approach is:
1. get text starting position
2. get mouse position
3. get all chars position and map them to their staring index 
4. when clicking on text get mouse position and get from the stored list the closest char position's index and move the cursors to that index.

I am blocked at the 3rd step. Is there a way to get each character from text its corresponding position ?

**This is the code I am using:**
 `fn map_chars_index_to_position(&self, ctx: &mut Context<'_>) -> Vec<(usize, f64)> {
        let text: String = ctx.widget().get::<String16>("text").as_string();
        // start x position of the cursor
        let start_position: f64 = ctx.get_widget(self.cursor).get::<Point>("position").x;
        // array which will hold char index and it's x position
        let mut position_index: Vec<(usize, f64)> = Vec::with_capacity(text.len());
       // add first position, no char
        position_index.push((0, start_position));
        
        ctx.get_widget(self.cursor).get_mut::<TextSelection>("text_selection").start_index = 0;
        ctx.get_widget(self.cursor).get_mut::<TextSelection>("text_selection").length = 0;

        for (index, _) in text.chars().enumerate() {
            / / increment text_selection length by 1 char
            ctx.get_widget(self.cursor).get_mut::<TextSelection>("text_selection").length = index + 1;
            // get bounding width of the text_selection, it should be the length of the text_selection only, not all the chars
            // but it gets always all the with of all selected chars
            let bound_width: f64 = ctx.get_widget(self.cursor).get::<Rectangle>("bounds").width;
            // get the end position for the current char
            let next_position: f64 = start_position + bound_width;
            // save the index and next_position
            position_index.push((index,next_position));
        }
        // reset text_selection length
        ctx.get_widget(self.cursor).get_mut::<TextSelection>("text_selection").length = 0;

        position_index
}`

I assume the element is not rendered in the loop and that's why it's bound position is not updated.
Is this a good approach or it is an easy way ?

Thanks.

**Comment by FloVanGH** [comment]
Hello @andreinbio,

thank you looks great so far.

`Context` has the method `render_context_2_d` to access the current RenderContext. With the `measure` you could measure the size of a text, also of a single character. Unfortantly the only solution now is to measure it on your `map_chars_index_to_position` by your self. An other property you will need is to left margin of the `text_block` child. Is describes the current offset of the text.

I hope this will help you.

**Comment by andreinbio** [comment]
Hello @FloVanGH ,
Thank you for the hint, it helped.
This is the PR with the new functionality: https://github.com/redox-os/orbtk/pull/213

**Comment by FloVanGH** [comment]
@andreinbio is merged thank you.
