### ISSUE TITLE
Feature requests project public for editing?

### ISSUE THREAD

**Issue by lukors** [redox-os/orbtk#206]
**Describe the bug**
I read the text on the "Projects" tab above, it says:

> Hello, Bonjour, Hola, Hej, Ni Hao, Ciao! Feel free to contribute and share your ideas and feature requests here.
>
> We will frequently go through all requests and make a choice of feature that are possible candidates for the next release.
>
> Please use the existing categories or create a new one if needed.

I get the impression we're meant to be able to make changes to it, but I can't find any way to do that. I can just read the existing feature requests.

This is just to let you know about this issue, I don't have an opinion on if having a public project for making feature requests in is a good idea or not, but the text should match the intention.

**Comment by FloVanGH** [comment]
We plan to use agil project management methods to speed up and better organize the development of OrbTk. But not everything is ready. This text is in artifact of this plan.

**Comment by FloVanGH** [comment]
I will close this now and add more details later.
