### ISSUE TITLE
ImageWidget disapears on click or resize of window

### ISSUE THREAD

**Issue by mpolosak** [redox-os/orbtk#208]
**Describe the bug**
ImageWidget disappears on click or resize of window when run in browser or as electron app. On Electron it even sometimes don't appear on start

**To Reproduce**

1. Run Image example in browser or as electron app
2. Click on image or resize window
3. Image disappear

**Expected behavior**
Should not disappear

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 76

**Comment by FloVanGH** [comment]
Thank you for the report. I will check and fix it.

**Comment by FloVanGH** [comment]
should be fixed
