### ISSUE TITLE
Deprecation and Build Failing

### ISSUE THREAD

**Issue by rushsteve1** [redox-os/orbtk#21]
The function `char_range_at` used in `text_box.rs` has been [deprecated as of Rust 1.9](https://doc.rust-lang.org/std/primitive.str.html#method.char_range_at) which is the cause of the current builds in both OrbTK and [OrbUtils](https://github.com/redox-os/orbutils) failing.

The recommended solution according to the documentation link above is to use a combination of the `chars()` and `len_utf8()` functions.

I am currently working on a few possible solutions on [my fork](https://github.com/rushsteve1/orbtk/tree/master) but have been running into a strange issue where the cursor does not move along as you type, thus typing backwards.

**Comment by jackpot51** [comment]
I have fixed this
