### ISSUE TITLE
Do you have plans to allow for custom input event loops / renderers?

### ISSUE THREAD

**Issue by mitchmindtree** [redox-os/orbtk#212]
For example, if I'm using `winit` in an existing project, would it be possible to add in an orbtk GUI and drive it forward by translating `winit` events to some orbtk input event type?

Similarly, does orbtk have a platform-agnostic rendering abstraction? Perhaps something like a mesh and some render commands? I'm curious if it's possible to write a custom renderer, e.g. as a wgpu render pass.

I noticed the goals of being cross-platform and modular, but I'm just trying to get a better gauge to what extent. Feel free to link me elsewhere if this has already been discussed!

**Comment by FloVanGH** [comment]
> For example, if I'm using winit in an existing project, would it be possible to add in an orbtk GUI and drive it forward by translating winit events to some orbtk input event type?

I think if you want to inject a window backend from outside like winit it is not possible now. What you have to do now is to fork OrbTk and add a solution where you can do it. But I imagine to have such a feature in OrbTk. But by the way I'm currently working on a alternative backend for OrbTk based on `glutin`. There is a translation from `winit` events to OrbTk events. And you also could inject custom event types to the event pipeline of OrbTk.

> Similarly, does orbtk have a platform-agnostic rendering abstraction? Perhaps something like a mesh and some render commands? I'm curious if it's possible to write a custom renderer, e.g. as a wgpu render pass.

Yes there is a abstraction for rendering. At the moment there a two different render backends, on based on `stdweb`  for web, `raqote` for all other platforms and `pathfinder` (wip) that supports also gpu rendering. You can found the `RenderContext2D` in the `render` sub-crate. It is the abstraction for 2D rendering. A `RenderContext2D` will follow.

> Similarly, does orbtk have a platform-agnostic rendering abstraction? Perhaps something like a mesh and some render commands? I'm curious if it's possible to write a custom renderer, e.g. as a wgpu render pass.

Most code of OrbTk is platform independent. Only the `shell` (window and events abstraction layer) and the `render` (render abstraction) layer contains platform specific code.
