### ISSUE TITLE
OrbTk apps crashes when left on its own

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#214]
**Describe the bug**
When I'm AFK for a minute, after coming back I see that a previously launched OrbTk app is disappeared and Visual Studio's terminal is full of stack traces.
I'm experiencing this the third time.

**To Reproduce**
1. Compile and run any example of orbtk or your own app using orbtk from Visual Studio's terminal with cargo run
2. Leave it alone for a few minutes (at least 10-15), go drink a coffee, or eat your lunch, etc,
3. Come back to the PC
4. See an error in Visual Studio's terminal and that app is closed.

**Expected behavior**
The apps should not crash, even if it's running for months, or year(s).

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1903
 - Version: 0.3.1-alpha1

**Additional context**
Backtrace logs attached.
[backtrace_1.txt](https://github.com/redox-os/orbtk/files/4673623/backtrace_1.txt)
[backtrace_2.txt](https://github.com/redox-os/orbtk/files/4673628/backtrace_2.txt)
[backtrace_3.txt](https://github.com/redox-os/orbtk/files/4673629/backtrace_3.txt)

**Comment by FloVanGH** [comment]
@kivimango thank you for the report, this also for the latest version.

**Comment by FloVanGH** [comment]
Could you check it again. I used the doit app the complete work day and it didn't crashed.

**Comment by kivimango** [comment]
I did not experience crashes for now. It was related to RenderingTasks, maybe the changes to the rendering backend fixed it somehow.
