### ISSUE TITLE
Very bad performance on all platforms except for Redox OS

### ISSUE THREAD

**Issue by PonasKovas** [redox-os/orbtk#216]
**Describe the bug**
After compiling the calculator example in release mode and running it on my Linux machine with wayland, I get very bad performance, horrific input latency.

I don't know what exactly causes it, because the same calculator app on my Redox OS VM works perfectly, without any lag whatsoever.

OS: Arch Linux (up to date)
WM: Sway (Wayland)

**To Reproduce**
1. Compile and run the calculator example
2. Try using it

**Expected behavior**
Should perform better I think.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25486263/83337536-f66f4b00-a2c4-11ea-98dc-5c94ad31dc73.gif)
Note that I am not holding the keys pressed, only short clicks. It only reacts after 1 sec minimum.

**Comment by nebkor** [comment]
For what it's worth, I have the same issue with the `widgets` demo on x11, using Mesa 20.0.4, and the Intel integrated graphics on a Thinkpad running Ubuntu 20.04.

**Comment by kivimango** [comment]
Duplicate of #179.
The next release will ship with a new rendering backend.

**Comment by jrmuizel** [comment]
On macOS it looks like this is caused by `window.limit_update_rate()` which causes minifb to limit the frame rate to no more than 15fps.

**Comment by komfluent** [comment]
I have the same issue on windows 10 home
Intel core i5
Nividia Geforce 940m

**Comment by FloVanGH** [comment]
Check: https://github.com/redox-os/orbtk/issues/179#issuecomment-640382888

**Comment by FloVanGH** [comment]
Check: https://github.com/redox-os/orbtk/issues/179#issuecomment-641712743

**Comment by FloVanGH** [comment]
should be fixed now.
