### ISSUE TITLE
Unreachable pattern in orbtk-shell src/event.rs

### ISSUE THREAD

**Issue by PonasKovas** [redox-os/orbtk#217]
**Describe the bug**
https://github.com/redox-os/orbtk/blob/develop/crates/shell/src/event.rs#L354
Pattern cannot be reached because the same pattern is present in [here](https://github.com/redox-os/orbtk/blob/develop/crates/shell/src/event.rs#L342)

**Comment by kivimango** [comment]
Some keys were missing which I needed support for the NumericBox, and there were some conflicts before merging #211.
What is the keycode/unicode (?) for the Numpad Slash key?  I cant find it.
Anyway, we need a better and more robust keyboard abstraction.

**Comment by PonasKovas** [comment]
> what is the keycode/unicode (?) for the Numpad Slash key

I'm pretty sure there's no such thing. Both the slash key and the numpad divide key correspond to the same character.

I could be wrong though.

**Comment by FloVanGH** [comment]
The issue should be fixed now. But @kivimango yes we need there a robuster solution.
