### ISSUE TITLE
numeric_box example crashed

### ISSUE THREAD

**Issue by adals** [redox-os/orbtk#219]
cargo run --example numeric_box

then increase the size of screen from right .. it will be crashed
my os macOs catalina

Running `target/debug/examples/numeric_box`
2020-06-01 20:51:10.789 numeric_box[10923:1965257] Names (null)
zsh: segmentation fault  cargo run --example numeric_box

**Comment by FloVanGH** [comment]
@adals thank you for the report. I have the same issue on macOS.

**Comment by michalsieron** [comment]
I have no issue on WSL with Xming. Also checked on Lubuntu with Virtualbox and there was also no issue except for terrible performance (Lubuntu itself runs fast, example is slow). Performance of release version is ok though.
Running latest version from repo.

**Comment by FloVanGH** [comment]
Should be fixed.
