### ISSUE TITLE
Breaking API changes

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#223]
## Intro

To stabilize the API on widget side I want to do some last breaking changes and simplify the current API. After that you should not expect major API on widget side before 0.4. After that API widget changes the API on state side will be extended also for simplification purposes, but it will be more extends than major breaking changes. 

I hope for your feedback.

### Old

```rust
Grid::create()
    .child(Button::create().text("Click me").on_click(...).build(ctx))
```
### New

```rust
Grid::create()
    .child(ctx, Button::create().text("Click me").on_click(...))
```

The old `child` method would be kept as  `child_entity:

*Signatures*

`fn child<W>(mut self, ctx: &mut BuildContext, child: W) -> Self where W: Widget;`
`fn child_entity(mut self, entity: Entity) -> Self;`

### Old

```rust
Button::create()
```

### New

```rust
Button::new()
```
### Old

```rust
Button::create().vertical_alignment(...).horizontal_alignment(...)
```
### New

```rust
Button::create().v_align(...).h_align(...)
```

### Old

```rust
widget!(
    /// The `TextBox` widget represents a single line text input widget.
    ///
    /// * CSS element: `text_box`
    TextBox<TextBoxState>: ActivateHandler, ChangedHandler, KeyDownHandler {
        text: String16,
        water_mark: String16,
       ...
    }
)
```

### New

```rust
#[derive(Widget, State, Handler)]
#[state = "TextBoxState"]
#[handlers = "Activate, Changed, KeyDown"]
pub struct TextBox {
        text: String16,
        water_mark: String16,
}
```

**Comment by valkum** [comment]
Can't we put the ctx into create now new?
`Widget::new(ctx: &mut BuildContext) -> Self`

And what about this widget macro replacement?

```
#[derive(Widget, State, Handler)]
#[state(TextBoxState)]
#[handlers(ActivateHandler, ChangedHandler, KeyDownHandler)]
pub struct TextBox {
        text: String16,
        water_mark: String16,
}
```

**Comment by FloVanGH** [comment]
@valkum 

> Can't we put the ctx into create now new?
Widget::new(ctx: &mut BuildContext) -> Self

Unfortunately that is not possible because of borrowing. 

> And what about this widget macro replacement?

That was just an idea. I'm not sure if it is better. Therefore I'm asking.

**Comment by rzerres** [comment]
for consitency with the overall rust style, i would prefere the macro replacement style @valkum  introduced.

**Comment by FloVanGH** [comment]
## First api update (live)

### create => new

Renamed all `create` methods to `new`. create is still available but is marked as `deprecated` and will be removed with 0.3.1-alpha4. 

#### Old

```rust
Button::create()
    .text("Click me")
```

#### New

```rust
Button::new()
    .text("Click me")
```

### vertical_alignment => v_align; horizontal_alignment => h_align

Renamed `vertical_alignment` method to `v_align` and `horizontal_alignment` to `h_align`. vertical_alignment and horizontal_alignment are still available but is marked as `deprecated` and will be removed with 0.3.1-alpha4. 

```rust
Button::create()
    .text("Click me")
    .vertical_alignment("center")
    .horizontal_alignment("center")
```

#### New

```rust
Button::new()
    .text("Click me")
    .v_align("center")
    .h_align("center")
```

### Grid simplification

Renamed `row` and `column` property of row and column builder to `add` and make the build method optional. `row` and column are marked as deprecated and will be removed with 0.3.1-alpha4.

#### Old

```rust
Grid::new()
    .margin(8.0)
     .columns(
          Columns::new()
               .column(132.0)
                .column(16.0)
                .column(132.0)
                .column(16.0)
                .column(132.0)
                .build()
     )
```

#### New

```rust
Grid::new()
    .margin(8.0)
     .columns(
          Columns::new()
               .add(132.0)
                add(16.0)
                .add(132.0)
                .add(16.0)
                .add(132.0)
     )
```

### WIP better widget access on states

#### old

```rust
impl State for MyState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
         ctx.get_widget(self.button).set("foreground, Brush::from("#000000");
         ....
    
```

#### new

```rust
impl State for MyState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context<'_>) {
         Button::get(ctx.get_widget(self.button)).set_foreground("#000000");
         ....    
```

### Some thounds

* I checked the replacement of `.child(Button::new().build(ctx))` with `.child(Button::new(), ctx)` but I found in a whole ui it makes the code very ugly.

* I checked also my suggestion:

```rust
#[derive(Widget, State, Handler)]
#[state(TextBoxState)]
#[handlers(ActivateHandler, ChangedHandler, KeyDownHandler)]
pub struct TextBox {
        text: String16,
        water_mark: String16,
}
```
but in practices I like more the `widget!` macro.

* From my perspective we could release 0.3.1-alpha3 with the current wip change and the new style system. At this point I would suggest to define the major part of the API as stable and for the main release of 0.3 only minor changes should be expected.

**Comment by FloVanGH** [comment]
## Update better widget access on states

Feedback please:

Old: https://gist.github.com/FloVanGH/c099bb55258d464b9529143231752b64
New: https://gist.github.com/FloVanGH/616944991949718a27067a31844331c2

**Comment by FloVanGH** [comment]
done
