### ISSUE TITLE
Does not work on Metal-less macOS

### ISSUE THREAD

**Issue by pheki** [redox-os/orbtk#226]
**Describe the bug**
Trying to run using the `0.3.1-alpha2` version will panic at `orbtk_shell::platform::WindowBuilder<A>::build` with `Failed to create window "Unable to open Window"` on Metal-less macOS

**To Reproduce**
1. Add `orbtk = "0.3.1-alpha2"` to your dependencies
2. Copy the minimal example
3. `cargo run`

**Expected behavior**
To work on any x64 macOS (`don't panic!()`)

**Desktop (please complete the following information):**
macOS 10.13 (High Sierra), with no Metal

**Additional context**
Support for non-metal macOS is missing from minifb (see https://github.com/emoon/rust_minifb/issues/140), but since it worked in 0.2 and older mac machines are pretty popular (as they still run fast and the upgrade cost is pretty high), I'm posting here to raise awareness.

Also, if this is intentional, it should be at least advertised in the "Platforms" section of the README.

**Comment by FloVanGH** [comment]
I’m working on an alternative backend. Could you check the pathfinder branch and run: cargo run — example widgets — features pathfinder and let me now if it run on your metalless macOS.

**Comment by pheki** [comment]
Very nice! It partially works (open and render widgets) with "Selected" incorrectly (?) over the list and 100% usage on one of my cores. I also cannot interact with anything, but its probably because its hanging the core.

Not sure if that's just the current state of the backend, but I can try to do some perf / flamegraph to identify the culprit.

![image](https://user-images.githubusercontent.com/19574371/84578955-35f76600-ada0-11ea-84bb-713e4c69642a.png)

**Comment by FloVanGH** [comment]
Ok really nice, thank you. Yes it’s the current state. I will continue my work on the new backend soon.

**Comment by FloVanGH** [comment]
@pheki could you also check the orbclient branch please? I have to check if it works also on metal less macOS.

**Comment by pheki** [comment]
Short answer: I think so.

Long answer:

It kind of works (takes very long to init and after that, when I move the mouse over it glitches), sometimes it hangs my CPU for seconds. I actually compiled on a newer macOS, in both debug and release mode (to try help with the CPU usage), while the hang seemed shorter on release the glitches are the same. On a newer mac (with metal) the glitch is a black screen.

<details>
<summary>Metal-less screenshots</summary>

![metal-less](https://user-images.githubusercontent.com/19574371/90474459-b2d5f180-e0fb-11ea-8064-765b19b6e7a1.png)
![metal-less-glitch](https://user-images.githubusercontent.com/19574371/90474461-b49fb500-e0fb-11ea-8940-bef5839c5825.png)

</details>

<details>
<summary>With Metal (also more recent macOS) screenshots</summary>

![metal](https://user-images.githubusercontent.com/19574371/90474481-bf5a4a00-e0fb-11ea-8b5c-9fb6b780e9ce.png)
![metal-glitch](https://user-images.githubusercontent.com/19574371/90474484-c08b7700-e0fb-11ea-9fcb-3e6374556a36.png)

</details>

**Comment by FloVanGH** [comment]
Could you recheck it please? It is now merged in develop.

**Comment by FloVanGH** [comment]
There are many improvements now. I close this now. If there are still issues you can reopen it.

**Comment by pheki** [comment]
Sorry for the delay... It works!

Thanks a lot 😄

**Comment by FloVanGH** [comment]
You're welcome.
