### ISSUE TITLE
Buttons draw over eachother when placed on a grid

### ISSUE THREAD

**Issue by Charles-Schleich** [redox-os/orbtk#229]
How can I set buttons to not draw over each other when placed on a grid in columns ?
And rather just fill up the width they are set to, and the next button gets drawn directly to the right.
I.e. TAB, CAPS, and space are longer than other keys
Space gets drawn,  then (ALTGR, FN, OPT,RCTRL) all get drawn ontop of the space bar which still extends outwards to the right after RCTRL. 

![image](https://user-images.githubusercontent.com/17414081/84597675-e8453100-ae65-11ea-8ca2-cc2a5c7bd38c.png)
```rust 
fn mk_row(){
    let kw = 48.0 ; //  Standard Key width
    // // Second Row
    let second_row_keys: Vec<(&str,i32,f64)>  = vec![("TAB",0,66.66) ,("Q",1,kw) ,("W",2,kw) ,("E",3,kw) ,("R",4,kw) ,("T",5,kw) ,("Y",6,kw) ,("U",7,kw) ,("I",8,kw) ,("O",9,kw) ,("P",10,kw) ,("[",11,kw) ,("]",12,kw) ,("ENTER",13,66.66) ];
    let second_row= make_row(ctx, second_row_keys);
   // add second_row to overall grid with other key rows 
}

fn make_row(ctx: &mut BuildContext, row_keys: Vec<(&str,i32,f64)> ) -> Grid {
    let key_w = _WIDTH * 0.0405;
    let mut row_columns= Columns::create();
    for _ in 0..row_keys.len(){ row_columns=row_columns.column(key_w); }

    let mut row =  Grid::create().columns(row_columns.build());
    for i in row_keys.iter(){
        let (key,pos,width) = i;
        let fkey = generate_character_button(ctx,key.to_string(),*pos as usize, *width);
        row = row.child(fkey);
    }
    row
}
```

Hopefully this helps someone else looking as well.

**Comment by FloVanGH** [comment]
In your case it would help to add `auto` columns to your grid:

```rust
for _ in 0..row_keys.len(){ row_columns=row_columns.column("auto"); }
```
Auto columns gets the width of the widgets element in the column.

If you want to add spacers between your buttons you could add spacer columns between the buttons:

```rust
for _ in 0..row_keys.len(){ row_columns=row_columns.column("auto").column(8.0); }

let mut row =  Grid::create().columns(row_columns.build());
for i in row_keys.iter(){
    let (key,pos,width) = i;
    let fkey = generate_character_button(ctx,key.to_string(),*pos as usize * 2, *width);
    row = row.child(fkey);
}
```

By the way nice project.

**Comment by Charles-Schleich** [comment]
This looks so much better, i was trying functions like `.clip` `.padding`.
Thank you @FloVanGH ! 
Great library, looking forward to using it more :+1:

**Comment by FloVanGH** [comment]
You’re welcome. Thank you I’m glad to hear that 🙂.
