### ISSUE TITLE
Crash message should be more informative

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#237]
# Context
When orbtk crashes due to developer error, e.g.: setting a property that does not exist, the panic message is:

> thread 'main' panicked at 'Entity 49 does not contain property type TypeId { t: 9785122672296426403 }', <::std::macros::panic macros>:5:6

# Problem description & Solution
I don't know what the concrete type or property is, I can only guess.
# Examples and MockUps
The panic message should be more informative, printing the concrete type/property, like:
> thread 'main' panicked at 'Entity 49 does not contain property type TypeId { "selected"}', <::std::macros::panic macros>:5:6

**Comment by FloVanGH** [comment]
@kivimango I'll add more informative message there. But for now to prevent that you could also use the new snake_case variant of a widget e.g. `button(ctx.widget()).set_text("Click")` or `Button::get(ctx.wiget()).set_text("Click")`. This two will automate generate for all widgets creates by the wdiget macro.

**Comment by FloVanGH** [comment]
Updates for some methods of `WidgetContainer`. More will follow.

**Comment by kivimango** [comment]
Thanks. I was about just sending a PR :).
Anyway, I tried to update to the latest version, but it breaks my custom theming, the default orbtk dark theme is loaded.
