### ISSUE TITLE
Thread listeners

### ISSUE THREAD

**Issue by Zoldszemesostoros** [redox-os/orbtk#243]
# Context

In which context or scenario will your feature/widget be used?
Almost every application that performs actions taking a long time (e. g. network requests). For example a chat application.

# Problem description & Solution

Describe your problem and possible solution here

It's very hard to modify the GUI from another thread. You can't do this directly, because of Rust's ownership system, and can't check the mpsc channels from the main thread, because .run() blocks this. So you'll end up with unsafe code, which is discouraged.

A possible solution is checking in every event loop for new messages, and call a callback if there are some.

# Examples and MockUps
```
use orbtk::prelude::*;
use std::sync::mpsc;
use std::thread;
fn main() {
	let (tx, rx) = mpsc::channel();
	thread::spawn(move || {
		/* Create a network socket, and notify the main thread about new messages via tx */
	});

	Application::new()
		.message_listener(rx, |message, states| {
			/* Do stuff with message, e.g. update the GUI if needed*/
			/* This callback is called on every new message */
		})
		.window(|ctx| {
			Window::new()
				.title("OrbTk - minimal example")
				.position((100.0, 100.0))
				.size(420.0, 730.0)
				.child(TextBlock::new().text("OrbTk").margin(4.0).build(ctx))
				.build(ctx)
		})
		.run();
}
```

If there is a similar feature, sorry for the issue.

**Comment by FloVanGH** [comment]
At the moment the build in mechanisms of OrbTk for Threading are very limited. In the next two weeks we will release 0.3.1-alpha-3 and after that version one of the main topics will be a comfortable way to run custom task synchronous and asynchronous from a widget state.

**Comment by kivimango** [comment]
I second that.It is essential for GUI applications to run certain (I/O) tasks on a separate thread to do not freeze the UI.
(and soon I will need that feauture in my app)

**Comment by shadiakiki1986** [comment]
Here is an example implementation with orbtk that runs tasks on a separate thread without freezing the UI:
[link](https://github.com/shadiakiki1986/orbtk-async-example/blob/master/examples/orbtk_oneButton_async.rs)

It just has 2 buttons:
 * Button 1 (S): Runs some syncronous code containing a "sleep" and shows how the GUI hangs
 * Button 2 (A): Runs the same sleep code in a separate thread and shows how the GUI doesn't hang
               Clicking button 2 (A) shows the async code display to stdout in the terminal from
               which the GUI was built/launched. Clicking it multiple times will repeat the async
               code.

**Comment by FloVanGH** [comment]
@shadiakiki1986 thank you very much for the example. With `0.3.1-alpha4` we will introduce a way to handle async task from a state.

**Comment by BlueSialia** [comment]
@shadiakiki1986 In your example "Async main: Sleep 3 seconds" gets immediately overwritten by "Async main: wake up". I think what @Zoldszemesostoros requires is not met with your example. Like, let's say instead of showing "Async main: wake up" what you want to show depends on the result of a function that takes a non-trivial amount of time, but you want it for the user to be able to keep interacting with the GUI.

**Comment by shadiakiki1986** [comment]
The example runs a separate thread for a calculation but doesn't send any
results back. I'm sure that it can be extended to send a result back using
the same idea of channels

**Comment by FloVanGH** [comment]
Check https://github.com/redox-os/orbtk/issues/305. It is now a lot of easier to send and receive messages async.
