### ISSUE TITLE
Widgets example panics when adding new element to list

### ISSUE THREAD

**Issue by michalsieron** [redox-os/orbtk#244]
**Describe the bug**
Widgets example panics when adding new element to list

**To Reproduce**
1. `git clone https://github.com/redox-os/orbtk`
2. `cd orbtk`
3. `cargo run --example widgets`
4. Click on '+' button in Items section

**Expected behavior**
Example showcasing that widgets are working should not panic.

**Screenshots**
```
thread 'main' panicked at 'Widget with name: ItemsWidget and entity: 102 does not contain property width type_id TypeId { t: 8766594652559642870 } for key: blub', /home/michal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
```

**Desktop:**
 - OS: Fedora Remix for WSL (Windows 10 v1909)
 - Version: 0.3.1-alpha3

**Additional context**
It seems that line 44 in _examples/widgets.rs_ 
```rust
ctx.child("items").set::<usize>("blub", len + 1);
```
is causing the panic

**Comment by FloVanGH** [comment]
fixed
