### ISSUE TITLE
Value of ONE_SCROLL is not universal (NumericBox widget)

### ISSUE THREAD

**Issue by michalsieron** [redox-os/orbtk#246]
**Describe the bug**
In source of `NumericBox` widget, value of `ONE_SCROLL` is not universal between systems, thus value inside of `NumericBox` may not be changed by multiples of `step`.

**To Reproduce**
1. `cargo run --example numeric_box`
2. Scroll with mouse wheel on numeric box
3. You may or not see the bug

**Expected behavior**
Value inside of `NumericBox` should be multiple of declared step. On my system it clearly isn't.
Also precision should be adjusted to size of the widget.

**Screenshots**
![screen](https://user-images.githubusercontent.com/54780569/86151546-247fbf00-baff-11ea-82e7-47b55bf56317.png)

**Desktop**
 - OS: Windows 10 v1909 (Fedora for WSL and Lubuntu on Virtualbox)
 - Version v0.3.1-alpha3

**Additional context**
I changed value of "how many lines to scroll each time" in Windows Settings and it doesn't seem to be connected to it.
Maybe it is something with mouse driver?

**Comment by FloVanGH** [comment]
@kivimango could you check it?

**Comment by kivimango** [comment]
yes, but it will take some time...

**Comment by michalsieron** [comment]
I found something. It's about X11 only, but it may explain some of this.
[Here](https://stackoverflow.com/questions/15510472/scrollwheel-event-in-x11) first comment under the answer says that X11 fires 2 events for one scroll: button press and release (that would explain why in my case single scroll had delta 2), because X11 treats mouse wheel as buttons 4 and 5 (not to confuse with actual buttons 4 and 5 on some mouses).

I can't find anything about Wayland or Windows though. I don't own an Apple machine so no idea what's going on there. Web target needs to be checked too, I guess.

**Comment by michalsieron** [comment]
Ok, I fired up VM with SwayWM to test Wayland and found that single scroll is there equal to 15.0 in this case.
Also not sure whether it's OrbTk, Sway or VM, but OrbTk apps (I checked widgets example) don't render correctly in window. They appear as if they are outside of the window and mouse cursor is not visible.

**Comment by michalsieron** [comment]
Also it seems, that in Windows using touchpad will not result in multiples of 12.0. Delta can take any value there, so `NumericBox` can take value different than **start** + **n** x **step**.

**Comment by kivimango** [comment]
the delta's values source is the minifb crate:
crates/shell/src/minifb/window.rs line 146.
fn get_scroll_wheel() declared in the rust_minifb crate: src/lib.rs line 516, which is calling the underlying platform-dependent code from the https://github.com/emoon/rust_minifb/tree/master/src/os module.

I think this should be delegated to minifb, NumericBox does not even compute the delta for itself, it is just using it.

**Comment by kivimango** [comment]
I think I solved it. since orbtk already fires a scroll event, I just need to change the value by step based on the delta is negative or positive.
I need to test it, I will fire up a Linux VM.
It happens on the wasm platform too.
And also pressing the +/- keys fires two events somehow.

**Comment by kivimango** [comment]
> Also precision should be adjusted to size of the widget.

I don't know why this happens, maybe related to TextBox or Grid.It is strange because in the widgets example the horizontal scrolling of the text in the TextBox is working.
