### ISSUE TITLE
good way to show error or other messages?

### ISSUE THREAD

**Issue by thivmcthiv** [redox-os/orbtk#250]
Hello again, 
I was wondering if there is a good way to show error messages in applications. for now, I am just using just new windows, with a function like this:

```rust
fn message_window(ctx: &mut Context, message: &'static str) {
    ctx.show_window(move |ctx| {
        Window::new()
            .title("Message")
            .position((170.0, 120.0))
            .size(130.0, 110.0)
            .resizeable(true)
            .child(
                TextBlock::new()
                    .text(message)
                .build(ctx)
            )
        .build(ctx)
    });
}
```
But that doesn't always seem to work, for example in a situation like this even though there is thread::sleep() both of the windows open at the same time after 3 seconds for some reason:

```rust
impl State for MainViewState {
    fn update(&mut self, _: &mut Registry, ctx: &mut Context) {
        if self.show_windows == true {
            message_window(ctx, "message");

            //simulate expensive function
            thread::sleep(Duration::from_secs(3));

            message_window(ctx, "other message");
            self.show_windows = false;
        }
    }
}
```

Is there some other way to show messages in a different window, or fix the fact that both windows show up at the same time?

**Comment by kivimango** [comment]
Maybe you could use a Popup.
https://github.com/redox-os/orbtk/blob/develop/crates/widgets/src/popup.rs
I will push an example of how to use it.

**Comment by FloVanGH** [comment]
@thivmcthiv the popup example is merged and on the master now.

**Comment by thivmcthiv** [comment]
Oh ok. thanks. (although I am now having issues with the popup widget) they dont seem to show up, even with .open(true) and .visibility(Visibility::Visible)
