### ISSUE TITLE
Seems like stack layout can't handle images

### ISSUE THREAD

**Issue by carlbean** [redox-os/orbtk#253]
**Describe the bug**
When i put one or more images in a Stack layout, they always end up at the start of the stack on top of everything.

**To Reproduce**
```rust
fn main() {
    Application::new()
        .window(|ctx| {
            Window::new()
                .title("OrbTk - image example")
                .position((100.0, 100.0))
                .size(1600.0, 840.0)
                .child(
                    Stack::new()
                        .child(TextBlock::new().text("top").build(ctx))
                        .child(ImageWidget::new().image("res/orbtk-space.png").build(ctx))
                        .child(ImageWidget::new().image("res/orbtk-space.png").build(ctx))
                        .child(TextBlock::new().text("bottom").build(ctx))
                        .build(ctx),
                )
                .build(ctx)
        })
        .run();
}
```
![Screenshot from 2020-07-06 21-33-49](https://user-images.githubusercontent.com/67280743/86633105-8a24ed00-bfd0-11ea-9723-1fff5c25e335.png)

 - OS: Ubuntu 18.04
 - Version [develop branch](https://github.com/redox-os/orbtk/tree/e8b0f9a3f8dc322414f1ea64de57f72979e17496)

My goal is to put multiple images below each other, but so far i didn't find a solution. Any suggestion appreciated!

Thank you for this great lib! I can't wait to see the future releases! :)

**Comment by FloVanGH** [comment]
Should be fixed now.

**Comment by carlbean** [comment]
Works great! Thanks a lot!!!
