### ISSUE TITLE
Popups don't show up

### ISSUE THREAD

**Issue by thivmcthiv** [redox-os/orbtk#254]
I am still familiarizing myself with this toolkit, and while I was trying to use the popup widget, I tried everything to make it appear,  but nothing worked.  

I tried using .open(true) and tried setting the visibility to visible, but that didn't work either. How do I actually get my popups to show up when a button is clicked or by any other means?
I also need a way to hide and show the popup on click, but I can't seem to figure that out either. (I hope people don't mind me asking too many questions here, I am searching the documentation thoroughly, but since I am not using orbtk-0.3.1-alpha2 that makes things difficult)

this didn't work:
```rust
Popup::new()
    .attach(Grid::row(0))
    .attach(Grid::column(0))
    .id("popup")
    .background(Brush::SolidColor(Color::rgb(77, 96, 128)))
    .border_radius(6.0)
    .border_brush(Brush::SolidColor(Color::rgb(12, 19, 31)))
    .visibility(Visibility::Visible)
    .open(true)
    .child(
        Button::new() 
            .text("button")
        .build(ctx)
    )
.build(ctx)
```

**Comment by FloVanGH** [comment]
@thivmcthiv you could ask everything. Essential you've got what you need to dive in deeper in OrbTk. @kivimango created an example for the popup you could check: https://github.com/redox-os/orbtk/blob/develop/examples/popup.rs. I hope this will help you.

**Comment by kivimango** [comment]
> I tried using .open(true) and tried setting the visibility to visible, but that didn't work either

If you check the popup.rs in the examples folder, you will see that create_popup() fn passes an Entity called target to the Popup builder. Then if you check the source code of the Popup in https://github.com/redox-os/orbtk/blob/develop/crates/widgets/src/popup.rs you will see that Popup has a property called **target**,
Then in the example's update() function,  two variables get declared:

```rust
let current_entity = ctx.entity; // current_entity will be the the **target** of the Popup
let build_context = &mut ctx.build_context(); /// we need a build context to attach the Popup to the Stack
```

create_popup() fn gets called with the previuos variables:

```rust
let popup = create_popup(current_entity, "Popup text", build_context);
```

then, finally, we attach the popup to the stack:
```rust
build_context.append_child(stack, popup);
```

> How do I actually get my popups to show up when a button is clicked or by any other means?

The example shows how to do that.

**Comment by thivmcthiv** [comment]
That example was a tremendous help, and I was able to make something like it with pattern matching by putting this in the update function: 
```rust

        if let Some(action) = &self.popup_action {
            match action {
                PopupAction::ShowError(s) => {
                    let container = ctx.entity_of_child(CONTAINER_ID).unwrap();
                    let current_entity = ctx.entity;
                    let build_context = &mut ctx.build_context();

                    let popup = create_popup(current_entity, &s, build_context);
                    build_context.append_child(container, popup);
                    self.popup = Some(popup);
                    self.popup_action = None;
                }
                PopupAction::ShowMessage(s) => {
                    println!("tried showing a message");
                    let container = ctx.entity_of_child(CONTAINER_ID).unwrap();
                    let current_entity = ctx.entity;
                    let build_context = &mut ctx.build_context();

                    let popup = create_popup(current_entity, &s, build_context);
                    build_context.append_child(container, popup);
                    self.popup = Some(popup);
                    self.popup_action = None;
                }
                PopupAction::Close => {
                    let container = ctx.entity_of_child(CONTAINER_ID).unwrap();
                    ctx.entity = container;
                    ctx.remove_child(self.popup.unwrap());
                    self.popup_action = None;
                }
            }
        }
```

Thanks so much for all the help!

**Comment by kivimango** [comment]
I'm glad it helped.
One more thing: I'm not really a fan of unwrapping().
You could do instead in init():
```rust
let self.container = ctx.entity_of_child(CONTAINER_ID).expect("Could not find Container!");
```
then in update():
```rust
let container = ctx.get_widget(self.container);
```

**Comment by thivmcthiv** [comment]
> I'm glad it helped.
> One more thing: I'm not really a fan of unwrapping().
> You could do instead in init():
> 
> ```rust
> let self.container = ctx.entity_of_child(CONTAINER_ID).expect("Could not find Container!");
> ```
> 
> then in update():
> 
> ```rust
> let container = ctx.get_widget(self.container);
> ```

Oh yeah thats a good idea. I'll probably have self.container be Option<Entity> so that in the case that the entity is not found I can handle the errors.
