### ISSUE TITLE
`TextBox` overwrites previous characters

### ISSUE THREAD

**Issue by michalsieron** [redox-os/orbtk#262]
**Describe the bug**
Selecting text in `TextBox` with `Ctrl+a` shortcut and then typing letters results in only one letter appearing.

**To Reproduce**
1. `git clone https://github.com/redox-os/orbtk`
2. `cargo clean`
3. `cargo run --example widgets --release`
4. Type some text into one of the `TextBox`es
5. Press `Ctrl+a`
6. Type some text
7. Only one character appears at a time and replaces previous one

**Expected behavior**
Text should appear normally

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363
 - Version: 0.3.1-alpha3 (newest from repo)

**Additional context**
Pressing backspace fixes it until next `Ctrl+a` and typing.
Also pressing backspace changes style of text cursor so that might be a hint.

**Comment by FloVanGH** [comment]
Fixed.
