### ISSUE TITLE
Best way to handle a key press?

### ISSUE THREAD

**Issue by matthewashton-k** [redox-os/orbtk#267]
What is the best way to detect if a key is down? I have tried a few things including using the KeyboardState struct, and having something like this in the update function where self.keyboard_state is of the type KeyboardState:

```rust
        if self.keyboard_state.is_shift_down() {
            println!("shift pressed")
        }
```

but I don't know how to call .set_key_state(Key::ShiftR, true) on self.keyboard_state when shift is actually pressed. Is there a different way to handle keyboard events, maybe with WindowAdapter?

**Comment by FloVanGH** [comment]
Keyboardstate is only a internal struct used by the window and the event system. 

A short example how to handle key press:

```rust
widget!(MainView: KeyDownHandler);

impl Template for MainView {
    fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
        self.on_key_down(|_, event| {
           match e.key {
                Key::ShiftR => // do someting
           }
        })
    }
}
```

**Comment by matthewashton-k** [comment]
Oh ok, that makes sense.
