### ISSUE TITLE
api crate docs does not reflect the directory hierarchy on the filesystem

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#284]
# Context
When generating documentation with ```cargo doc --no-deps --open```, in the api crate only the widget module is shown.

# Problem description & Solution
There are more modules like event, layout, render_object.I wanted to make a link in the Template trait's docs to the render_objects module, but it is not resolved (all of the render objects, layouts etc "flushed" in the api module, they are not in their separate modules.

Solution: all struct, traits, etc should be organized in the module system like they are on the filesystem.

![api_module](https://user-images.githubusercontent.com/18540032/88774501-d30d3300-d183-11ea-8b63-18ab86e9bf97.jpg)

**Comment by FloVanGH** [comment]
Thank you. I will fix that for the next release.

**Comment by FloVanGH** [comment]
done!
