### ISSUE TITLE
Multiple lines in a TextBlock

### ISSUE THREAD

**Issue by thivmcthiv2** [redox-os/orbtk#285]
Hello all, 

Is there any way to have multiple lines of text in a TextBlock? I tried the usual escape characters (\n \r) but it didn't work to make a new line. Is there any way to do this?

**Comment by kivimango** [comment]
Hello.
I think this is currently not possible. We will fix this soon.

(For a workaround, you could try splitting the text on \n or \r characters, and create a new TextBlock for every slice, then placing the TextBlocks on top of each other in a Stack with spacing 0.

**Comment by thivmcthiv2** [comment]
Oh ok. Thanks
