### ISSUE TITLE
Correct way to use ItemsWidget?

### ISSUE THREAD

**Issue by thivmcthiv2** [redox-os/orbtk#286]
Hello! a bit of a newbie question here, but I'm trying to figure out how to effectively append widgets into an ItemsWidget inside of  a popup.     I saw how this was done in the widgets.rs example, but frankly I don't completly understand it :) I assume that I need to use the items_builder method like this: 
```rust
            .items_builder(
                move |bc, index| {

                    println!("called .items_builder");
                    let text = bc.get_widget(id).get::<HashMap>("list")
                    .clone();

                    TextBlock::new().margin((0, 0, 0, 2)).text(text).build(bc)
                }
            )
```

to the best of my knowledge, the .items_builder method is what appends the entities to the ItemsWidget, but if I have a function, something like this to create a popup: 
```rust

fn data_popup(target: Entity, build_context: &mut BuildContext, data: HashMap<String, f64> ) -> Entity {
    Popup::new()
    .target(target)
    .open(true)
    .width(300.0)
    .padding(8.0)
    .height(350.0)
    .child(
        ItemsWidget::new()
            .margin((0, 0, 0, 8))
            .padding(8.0)
            .height(100.)
            .width(260)
            .enabled(true)
            .id("items")
            .child(
                Button::new()
                .text("Close")
                .v_align("bottom")
                .h_align("center")
                .max_width(80.0)
                .on_click(
                    move |states, _| {
                        states.get_mut::<MainViewState>(target).popup_action(PopupAction::Close); // this will close the popup when update() is run
                        true
                    }
                )
            .build(build_context)
            )
            .items_builder(
                move |bc, index| {
                    let fetched = bc.get_widget(target).get::<HashMap<String, f64>>("list")
                    .clone();

                    println!("the fetched is: {:?}", fetched);
                    TextBlock::new().margin((0, 0, 0, 2)).text(format!("{:?}", fetched)).build(bc)
                }
            )
        .build(build_context)
    )
    .build(build_context)
}
```

I call this function, doing something like this in the update function where data is of the type Hashmap<String, f64>:

```rust

                    let container = ctx.entity_of_child(INPUTS_CONTAINER).unwrap();
                    let current_entity = ctx.entity;
                    

                    for x in data {
                        main_view(ctx.widget()).list_mut().insert(x.0.to_string(), *x.1); // puts the data variable into the list field of MainView
                    }

                    println!("[*] adding {:?} to list", main_view(ctx.widget()).list());
                    let build_context = &mut ctx.build_context();

                    let popup = data_popup(current_entity, build_context, data.clone());
                    println!("[*] showing data popup");
                    build_context.append_child(container, popup);
``` 
after the code above is executed, the popup appears, looking like this: 

![image](https://user-images.githubusercontent.com/55366321/89353863-999d6180-d674-11ea-8e11-e664a5362d80.png)

I'm probably not using the .items_builder correctly. What is the correct way to use ItemsWidget?

**Comment by kivimango** [comment]
You need to set the ```count``` property on the ItemsWidget when you add items to it.

in data_popup() on ItemsWidget:
```rust
 ItemsWidget::new()
            .count(data.len())
            .margin((0, 0, 0, 8))
            .padding(8.0)
            .height(100.)
            .width(260)
            .enabled(true)
            .id("items")
```

Otherwise, the ItemsWidget won't update itself because both the state's value and the widget's property is 0.
[ItemsWidget.rs](https://github.com/redox-os/orbtk/blob/develop/crates/widgets/src/items_widget.rs) line 14.

I will add some documentation and an example of how to use it

**Comment by thivmcthiv2** [comment]
Oh ok, so the count is  incremented each time it is built using: 

```rust
let len = main_view(ctx.widget()).list().len();
items_widget(ctx.child("items")).set_count(len + 1);
```

the only problem with that is that in my case, I have to use the data_popup() function to create a popup, and if I add ```ctx: Context``` as a parameter, that causes a lot of borrowing and lifetime issues since ctx has to explicitly be Context<'static>,  and if I want to pass a reference to ctx into the data_popup function instead, then it has to be 'static as well, which causes issues. Is there any way that I can increment the counter in a different way?

**Comment by thivmcthiv2** [comment]
Oh wait, nvm I figured it out. Thanks for all of the help!

**Comment by kivimango** [comment]
> Oh ok, so the count is incremented each time it is built using:

No, not really.The `count` property is the count of the items in the ItemsWidget.So if you set the count property to 4, it will call the `items_builder()` 4 times, and builds and displays 4 children.

> if I add ctx: Context as a parameter, that causes a lot of borrowing and lifetime issues since ctx has to explicitly be Context<'static>

I think `Context` does need to be static. All you need is a mutable reference: `ctx: &mut Context` in the data_popup() fn's signature.

**Comment by FloVanGH** [comment]
@thivmcthiv2 could we close this issue or do you have any further questions.

**Comment by thivmcthiv2** [comment]
I dont have further questions about the widget. Thanks for the help!
