### ISSUE TITLE
[Question] There is a way to get the "real size" of a widget from context?

### ISSUE THREAD

**Issue by uniformbuffer** [redox-os/orbtk#289]
Hi,
i would like to know if there is a way to get the "real size" of a widget from the entity using `Context` (using something like `ctx.get_widget(entity).clone::<Rectangle>("real_size")`).
For "real size" i mean the size that is finally displayed.
I know that is possible to get the `bounds`, that is the area that the widget could occupy.
Then there is the `h_align` and `v_align` that manage the alignment inside the `bounds`.
There is also the `position` that is the position calculated after the widget has been aligned inside the `bounds`.
Unfortunatly i have not found a way to get the effective size.

Thanks for the attention,
Have a good day

**Comment by FloVanGH** [comment]
Hi,
you could read the real size of a widget (finished calculated size) on the `update_post_layout` method of the state. There the width and height of `bounds` represents the real size. `position` is only an internal property that is used to draw the widgets on the right position.

**Comment by uniformbuffer** [comment]
> There the width and height of `bounds` represents the real size

Oh, i didn't know that. Thanks!
