### ISSUE TITLE
Nesting a Grid inside a Stack displays the rest at the wrong position

### ISSUE THREAD

**Issue by ChatPion** [redox-os/orbtk#299]
**Describe the bug**
When nesting a Grid inside a Stack, the elements of the stack after the Grid are not in the correct position.

**To Reproduce**
For example, this code produces the following image :
```rust
use orbtk::prelude::*;

fn main() {
    Application::new()
        .window(|ctx| {
            Window::new()
                .size(420, 730)
                .child(
                    Stack::new().child(
                        Grid::new()
                        .rows(Rows::create().push(30).push(40))
                        .columns(Columns::create().push("*"))
                        .child(Button::new().text("Button 1").attach(Grid::row(0)).build(ctx))
                        .child(Button::new().text("Button 2").style("button_primary").attach(Grid::row(1)).build(ctx))
                        .build(ctx))
                    .child(
                        Button::new().text("Button 3").attach(Grid::row(2)).build(ctx)
                    )
                    .build(ctx)).build(ctx) 
        })
        .run();
}

```
![2020-08-20_15-42](https://user-images.githubusercontent.com/3697923/90777448-ba63e900-e2fb-11ea-9678-8321199267ab.png)

**Expected behavior**
In my example, `Button 3` should be below `Button 2` (the yellow one).

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Using the latest version (develop) of OrbTk

**Comment by FloVanGH** [comment]
Thank you for the report. @kivimango maybe it is connected to the grid `auto` issue.

**Comment by ChatPion** [comment]
I think it is indeed linked to #170 
By the way, it is the same with horizontal Stack, thus a fix for the aforementioned issue should cover both auto height and width.

**Comment by arctic-alpaca** [comment]
![buttons](https://user-images.githubusercontent.com/67190338/94987332-0eeabd00-0566-11eb-9205-9f3232c369b1.PNG)
This is what it looks like currently, so this might have been fixed by the `auto` fix.

> By the way, it is the same with horizontal Stack, thus a fix for the aforementioned issue should cover both auto height and width.

@ChatPion I'm not sure what you mean by horizontal Stack, could you check whether you have any remaining issues on your side?

**Comment by kivimango** [comment]
> 
> 
> ![buttons](https://user-images.githubusercontent.com/67190338/94987332-0eeabd00-0566-11eb-9205-9f3232c369b1.PNG)
> This is what it looks like currently, so this might have been fixed by the `auto` fix.
> 
> > By the way, it is the same with horizontal Stack, thus a fix for the aforementioned issue should cover both auto height and width.
> 
> @ChatPion I'm not sure what you mean by horizontal Stack, could you check whether you have any remaining issues on your side?

I think he is referring to a Stack with orientation("horizontal") property.
Now it looks like this:
![hor_Stack](https://user-images.githubusercontent.com/18540032/94988198-d2ba5b00-056b-11eb-81c0-0e436602a09c.jpg)

**Comment by kivimango** [comment]
Anyway, this example code is wrong on multiple points:
* There are two rows created, but the third button attached to the third row.
* The third button attached to a grid that does not exist? The grid definition ends at line 19.

**Comment by ChatPion** [comment]
@kivimango Concerning your first two points, I do agree I made a mistake and there shouldn't be a `.attach(Grid::row(2)` for the third button, but the example code gives the intended result after removing it so it isn't an issue in the end. As for your last point, I'm trying to embed a pad-like widget (which is essentially a grid) inside a stack. I'm using a stack because it does well what I want: stacking widgets, regardless of their type.

Anyway, it looks like I don't have any issues on my side @arctic-alpaca , thank you!

**Comment by kivimango** [comment]
Can you share a picture please how does it look like now?

**Comment by ChatPion** [comment]
If you mean the fixed example code, it looks exactly like the two pictures above.
