### ISSUE TITLE
Can't override property from theme file

### ISSUE THREAD

**Issue by ChatPion** [redox-os/orbtk#300]
**Describe the bug**
I can't override a property that is already defined in a RON file with `.style()`. I don't know whether it is by design or it is a bug.

**Example**
style.ron
```
Theme (
    styles: {
        "example": (
            properties: {
                "font_size": 20
            }
        )
    }
)
```

main.rs
```rust
use orbtk::prelude::*;
use orbtk::theming::config::ThemeConfig;

static THEME: &str = include_str!("../style.ron");

fn theme() -> Theme {
    Theme::from_config(ThemeConfig::from(THEME))
}

fn main() {
    Application::new()
        .theme(theme())
        .window(|ctx| {
            Window::new()
                .size(420, 730)
                .child(TextBlock::new()
                       .style("example")  // (1)
                       .text("Test")
                       .font_size(10)
                       .build(ctx))
            .build(ctx)
        })
        .run();
}
```
If I run this file as is, I see this:
![2020-08-21_13-44](https://user-images.githubusercontent.com/3697923/90887369-86003380-e3b4-11ea-8e09-7bf76bcb340a.png)

But if I comment (1), I see this:
![2020-08-21_13-44_1](https://user-images.githubusercontent.com/3697923/90887411-97e1d680-e3b4-11ea-809d-8ccb7f9cd446.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Using the develop version of OrbTk

**Comment by kivimango** [comment]
This should be documented in the Theming section...

**Comment by vessd** [comment]
It looks like I can't even change the size of the button without defining my theme...

**Comment by rzerres** [comment]
Either you use the `style` property inside a widget, **or** you define all `desired properties` inside the view code. Style will take **precedence** if it is defined!
And yes, you will manage your style properties via a theme. You are free to enhance the provided, default toolkit themes with your overwrites. Please console the documentation or example section
