### ISSUE TITLE
Acces to raw window handle

### ISSUE THREAD

**Issue by oskargargas** [redox-os/orbtk#302]
# Context

I'd like to pass native/raw window handle to platform specific methods outside of scope of OrbTK. In specific I'd like to pass window created by OrbTK to MS Windows Raw Input to get access to Joystick events, etc. Raw Input requires HWND handle. 

# Problem description & Solution

Native/raw window handle is not publicly accessible (or it's accessible in some way I can't find). Solution would be to give access to raw window handle (HWND in case of MS Windows) which is accessible via `application.shell.window_shells[x].window`

![raw_window_handle_in_memory](https://user-images.githubusercontent.com/839839/90958942-9fc67700-e497-11ea-9ea5-42f22dd91526.png)

If I'm mistaken and there is some way to access it right now I'll be glad to learn it. :)

**Comment by FloVanGH** [comment]
`RawWindowHandle` is now available on the `Context` struct. You could check it on the `orbclient` branch and it will be soon available on the develop branch.

**Comment by oskargargas** [comment]
Thank you, will check in coming week!
