### ISSUE TITLE
Slow performance when dragging slider

### ISSUE THREAD

**Issue by emoon** [redox-os/orbtk#306]
**Describe the bug**

When testing the `widgets` example and dragging the slider the update takes 20 ms in total which is quite slow. Also dragging the controller itself is very laggy.

**To Reproduce**
1. `cargo run --release --examples widgets`
2. Drag slider
3. Notice that the update is being slow.

**Expected behavior**

It's expected that the update is fast and doesn't take 20 ms on a fast PC

**Desktop (please complete the following information):**
 - OS: Ubuntu 18, Threadripper 32 cores, 3.2 Ghz CPU

**Additional context**
I added this temporary code inside `orbclient/mod.rs`

```Rust
            let prev_time = Instant::now();
            for i in 0..self.window_shells.len() {
                let mut remove = false;
                if let Some(window_shell) = self.window_shells.get_mut(i) {
                    window_shell.update();
                    window_shell.render();

                    window_shell.update_clipboard();
                    window_shell.drain_events();
                    window_shell.receive_requests();

                    if !window_shell.is_open() {
                        remove = true;
                    }
                }

                if remove {
                    self.window_shells.remove(i);
                    break;
                }
            }

            self.receive_requests();

            let current_time = Instant::now();
            println!("duration {:#?}", current_time - prev_time);
```

Output (high numbers while dragging)

```
duration 11.602µs
duration 10.219µs
duration 12.534µs
duration 43.883µs
duration 25.39321ms
duration 19.554445ms
duration 20.057975ms
duration 20.025733ms
duration 19.956963ms
duration 20.024992ms
duration 20.132557ms
duration 20.805289ms
duration 20.308552ms
duration 20.084406ms
duration 19.612777ms
duration 20.152404ms
duration 20.388825ms
duration 19.576738ms
duration 19.993302ms
duration 19.52479ms
```
A quick profile indicates that over half of the time is spent inside malloc (!)

**Comment by FloVanGH** [comment]
Hey, thank you for the your report. Which tool did you use. More performance will be also part of the next release. I hope we could also fix the issue with true slider. You info will help.

**Comment by emoon** [comment]
Thanks! I used `perf` as described here http://www.brendangregg.com/perf.html#TimedProfiling I didn't investigate in much detail tho

**Comment by FloVanGH** [comment]
Thank you

**Comment by FloVanGH** [comment]
I used `cargo instrument` a profiling tool for macOS. I looks like the most time is spent inside the `compose` method of raqote. I've created an issue there: https://github.com/jrmuizel/raqote/issues/159

**Comment by FloVanGH** [comment]
Having the same issue on the web port.

**Comment by FloVanGH** [comment]
On release mode with PR #324 it is a lot of faster. On debug it is a little bit faster.
