### ISSUE TITLE
keypad input not work , ctrl+a , ctrl+c , ctrl+v not work in win10

### ISSUE THREAD

**Issue by payallmoney** [redox-os/orbtk#311]
code is examples/widgets.rs   , win10 
1, input number using keypad not work , nothing inputed  (TextBox  PasswordBox )
2, ctrl+a  , ctrl+c , ctrl+v not work

**Comment by FloVanGH** [comment]
Hi thank you for your report. What version do you checked `0.3.1-alpha3` or the `develop` branch?

**Comment by FloVanGH** [comment]
Hi thank you for your report. 

Checked it now on Windows 10.

> 1, input number using keypad not work , nothing inputed (TextBox PasswordBox )

I have the same issue, it will be fixed.

> 2, ctrl+a , ctrl+c , ctrl+v not work

everything worked as expected. Do you use the `develop` branch? You could check to run `cargo clean` before rebuilding?

Thanks

**Comment by payallmoney** [comment]
> everything worked as expected. Do you use the `develop` branch? You could check to run `cargo clean` before rebuilding?
I tryed  cargo clean  , nothing changed  , keypad and ctrl+a ,ctrl+c , ctrl+v still not work .
My Windows 10 version is 19041.208
orbtk version  v0.3.1-alpha4 (https://github.com/redox-os/orbtk.git?branch=develop#460029e3) 
Cargo.toml [dependencies]   orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }
rust version 1.47.0-nightly (39d5a61f2 2020-07-17)

**Comment by FloVanGH** [comment]
I've tested it on a Windows VM and a native windows with the same rust version, but it works. I'm in a rewrite of the internal text input. Maybe you could check it again after it is completed?

**Comment by payallmoney** [comment]
> I've tested it on a Windows VM and a native windows with the same rust version, but it works. I'm in a rewrite of the internal text input. Maybe you could check it again after it is completed?

Ok , I will check it again after it is completed .
Thanks for you work .

Please forgive me for my poor English .

**Comment by FloVanGH** [comment]
No problem.

The PR is merged you can check it.

**Comment by FloVanGH** [comment]
Any update?

**Comment by payallmoney** [comment]
> Any update?

the widgets.rs has something wrong until today's update .
i tested ,  ctrl+a , ctrl+c , ctrl+v is working now . 
keypad still not working

**Comment by FloVanGH** [comment]
I think I'm not able to check it correctly. I have only Windows in a VM and I think that behaves not the same as a native Windows. I will check what I can do. 

I think the source of the issues is the OrbClient backend.

**Comment by arctic-alpaca** [comment]
I tested my keyboard with the OrbClient simple example and the following keys did not register:
- numpad with numlock on (with numlock off, the "arrowkeys" 2, 4, 6 and 8 register as scancode 80, 75, 77 and 72)
- `End` only registers as `pressed: false` all other keys register first as true when pressed, then false when released
- `Insert` did not register at all
- `NumLock` and `CapsLock` don't register as keys pressed, but work in changing registered input (e.g. from `a` to `A`)
- `Alt GR` registers as two keys at once, 29 and 56. 56 is also left `Alt`
- `<` key did not register at all

**Comment by FloVanGH** [comment]
I have now also a native window. That will help me to test better on windows.
