### ISSUE TITLE
Calculator works very slow and not always gets input

### ISSUE THREAD

**Issue by qarmin** [redox-os/orbtk#315]
**OS**
Ubuntu 20.04
X11 Gnome 3.36.4
Nvidia GTX 970 - 440 -propertiary drivers

**Describe the bug**
I'm choosing GUI library for my project and tried calculator from examples, but it works very very slow and doesn't always register mouse button(on gif I clicked at every single one button, but only sometimes number shows).

There is no difference between debug and release build.

![jfile](https://user-images.githubusercontent.com/41945903/92003810-b98e7680-ed41-11ea-90e9-59b8942608cf.gif)

**Orbtk**
0.3.14-alpha4
2ca5c6efe1f9f2d91fe5955b6f0d09056e9e0f51

Hotspot perf report(https://github.com/KDAB/hotspot)
![Zrzut ekranu z 2020-09-02 18-33-44](https://user-images.githubusercontent.com/41945903/92011079-d8ddd180-ed4a-11ea-883f-7aa6e59ea5fd.png)

**Comment by FloVanGH** [comment]
Thank you for the report maybe it is connected to issue #314 (memory leak) on Linux. We are working on alternatives to the current backend but I will also check to fix this. 

What display server are you using?

**Comment by qarmin** [comment]
X11 - Gnome 3.36.4

**Comment by FloVanGH** [comment]
Thanks.

**Comment by qarmin** [comment]
This commit caused also problems with other demos like  `tab_widget`

**Comment by FloVanGH** [comment]
@qarmin thank you very much. This will speed up the fix a lot. I finish one task I'm currently work on and after that I will fix this.
