### ISSUE TITLE
Add images for examples

### ISSUE THREAD

**Issue by qarmin** [redox-os/orbtk#318]
For some(or all) examples should be provided images to show users what should expect.
For now examples are rather basic, but with time should look better.

Also there there should one or more bigger applications in examples folder, to be able to easy check regressions without needing testing all test programs.

![Calculator](https://user-images.githubusercontent.com/41945903/92233419-8f0efb80-eeb0-11ea-98b8-1068e9444bf7.png)

(Probably I missclicked and this should be a feature proposal, not a bug)

**Comment by FloVanGH** [comment]
Thank you that's a great idea.

I also like your suggestion for a complex example. I have on mind a rewrite of the widget example, take TabsWidget as main navigation with categories like `Button`, `Text` and `Lists` and add all available widgets there. Also with representation of edge cases like a empty list and a list with many entries.

**Comment by kivimango** [comment]
Where the pictures should go? In the README, or in the examples folder or elsewhere?

**Comment by qarmin** [comment]
I think that README is good place to put it there because it will be easy to see images.
I wouldn't put this images into repository, because they will took a lot of space, but only links from github user content(created by dragging files to issue like above) should be provided.

**Comment by FloVanGH** [comment]
Image should be stored in the redox asset repo like the on on the main Readme.

Suggestion how to handle it one the examples Readme:

# widgets example 

To start the example run `cargo run —examples widgets —release` on the root of the repository 

Image

**Comment by FloVanGH** [comment]
I think we should remove some of the examples. I work at the moment on a complete showcase examples with all widgets represented.

**Comment by kivimango** [comment]
> I work at the moment on a complete showcase examples with all widgets represented.

Should I wait for it,  or I could start taking pictures ?

**Comment by FloVanGH** [comment]
@kivimango I think we can reduce the examples to the following:

* calculator 
* minimal
* mutli_window
* overlay
* settings
* showcase

I will integrate the other examples in the showcase. Except of the showcase example you can start with the screenshots. Thank you 🙂.

**Comment by kivimango** [comment]
calculator already has an image, I'm skipping the minimal example, it is looking bad, it justs a TextBlock.
By the way, I had issues with the multi_window example. it cannot be closed, and when I click on the buttons, nothing happens.

**Comment by FloVanGH** [comment]
It's ok to skip the minimal example. Yeah I know the Probleme with the multi_window example. There is also an issue.
