### ISSUE TITLE
Text goes beyond tab when using close_button(false)

### ISSUE THREAD

**Issue by qarmin** [redox-os/orbtk#320]
Ubuntu 20.04 X11
Orbtk - https://github.com/redox-os/orbtk/commit/13db987a41406523430cd8368c803a344b6c336b

**Describe the bug**
When I use `.close_button(false)` on tab demo, then text start to go over the end of tab

**Screenshots**
Wrong behavior without X
```
                    TabWidget::new()
                        .tab(
                            "Duplicate Finder",
                            TextBlock::new().text("Tab content 1").build(ctx),
                        ).close_button(false)
                        .tab(
                            "Empty Folders",
                            TextBlock::new().text("Tab content 2").build(ctx),
                        )
                        .build(ctx),
```
![Zrzut ekranu z 2020-09-05 11-39-23](https://user-images.githubusercontent.com/41945903/92302606-c1caf980-ef6d-11ea-891e-62d88e73a656.png)
Correct behaviour with X
```
                    TabWidget::new()
                        .tab(
                            "Duplicate Finder",
                            TextBlock::new().text("Tab content 1").build(ctx),
                        )
                        .tab(
                            "Empty Folders",
                            TextBlock::new().text("Tab content 2").build(ctx),
                        )
                        .build(ctx),
```
![Zrzut ekranu z 2020-09-05 11-39-36](https://user-images.githubusercontent.com/41945903/92302615-c98a9e00-ef6d-11ea-94c4-812c0275d122.png)

**Comment by FloVanGH** [comment]
You diligent 🙂. Thank you. I will fix this soon. There is also an Problem if you click on the close button . The close button is drawn out of bound of the tab.

**Comment by qarmin** [comment]
Still happens with master

Steps to reproduce
```
git clone https://github.com/qarmin/czkawka.git
cd czkawka/czkawka_gui_orbtk
cargo build --release
cd ../target/debug/cargo_gui_orbtk
```
This line should be changed to test behaviour
https://github.com/qarmin/czkawka/blob/806ee945666aeb3d9cfb1de00d09f8b93c0ba0f8/czkawka_gui_orbtk/src/main.rs#L70

**Comment by FloVanGH** [comment]
It is fixed now only in the develop branch. It will be merged in the master with the next release.

**Comment by qarmin** [comment]
Oh, I was almost sure that `orbtk = {git = "https://github.com/redox-os/orbtk"}` take the latest version of orbtk(some repositories uses as main branch `develop` and doesn't have master branch)
