### ISSUE TITLE
When to support chinese characters in widgets?

### ISSUE THREAD

**Issue by chn-cutelotus** [redox-os/orbtk#323]
:)

**Comment by FloVanGH** [comment]
I hope soon 😬. I checked the Noto font https://www.google.com/get/noto/. But it looks like that the font crate we are using `RustType` is not able to draw the chinese glyphs from the font. Maybe we have to switch to an other crate. I let you know if there are any updates!

**Comment by FloVanGH** [comment]
We will check alternatives. @sandmor suggested to check https://crates.io/crates/fontdue.

**Comment by kivimango** [comment]
The other problem with the Noto Font is its size: its huge, around 15-16 mb uncompressed (bigger than the whole project)

**Comment by chn-cutelotus** [comment]
Thanks for above information.

**Comment by chn-cutelotus** [comment]
It seems Chinese characters can be rendered in current Example of "Canvas"  which uses class RenderContext2D instead of TextBlock. Are there any plans of include similar function in class TextBlock ?

**Comment by FloVanGH** [comment]
It's a matter of the correct font. I will do some research what is the best solution. But it is already possible to extend a theme with custom fonts if that is something that helps you.

**Comment by kivimango** [comment]
Somebody mentioned a font in the comments, I will try to add to orbtk, but im busy right now.
The real solution would be to integrate font-rs, and provide API to developers to load custom fonts.

**Comment by rzerres** [comment]
This is a block from 2012 but seems to be quite acorate and still up to date.
[Kendra Schaefer: Standard Web-Fonts](http://kendraschaefer.com/2012/06/chinese-standard-web-fonts-the-ultimate-guide-to-css-font-family-declarations-for-web-design-in-simplified-chinese)

We might create feature lables to include a standard font for foreign languages (chinese, thai, hebrew, etc.) that are interacting with the localization and theme modules?
