### ISSUE TITLE
Invalid text wraps in TextBox

### ISSUE THREAD

**Issue by qarmin** [redox-os/orbtk#325]
**Describe the bug**
Text strange overlaps when user provide too big input

**To Reproduce**
```
git clone https://github.com/qarmin/czkawka.git
cd czkawka/czkawka_gui_orbtk
cargo build --release
cd ../target/debug/cargo_gui_orbtk
```
2. Press any key for a long time

**Screenshots**
![jfile](https://user-images.githubusercontent.com/41945903/92412118-f21bbf00-f14a-11ea-9d86-57bb986bf780.gif)

**Desktop (please complete the following information):**
Ubuntu 20.04 X11

**Comment by FloVanGH** [comment]
@sandmor could it be connected to the new multline feature? Otherwise it could be a wrong behavior of the text offset because the layout in this example is broken.

@qarmin there is a also a problem with your layout. The `TextBox` is cut off at the end. Without it this strange behavior should not be occur.

**Comment by sandmor** [comment]
@FloVanGH According to the [sole commit of that PR](https://github.com/redox-os/orbtk/commit/714f7ed2514513b95846ca2c9ed3aff46f883e23), there is not one modification on the text layout that involves the x-axis, and the editions on the text render object only splits the text according to \n, my PR not is implicate

**Comment by arctic-alpaca** [comment]
The same behavior can be seen when resizing the widgets example. When the `TextBox` widget is cut off, the text extends on the opposite site. The same things happens with the `ListView` item texts.
![orbtk_cutoff](https://user-images.githubusercontent.com/67190338/93665274-76d4da00-fa75-11ea-85ef-2de0c27826cf.png)

**Comment by FloVanGH** [comment]
Thank you I will fix that.

**Comment by FloVanGH** [comment]
fixed
