### ISSUE TITLE
TextBox doesn't back to initial box when removing text

### ISSUE THREAD

**Issue by qarmin** [redox-os/orbtk#326]
**Describe the bug**
Too long text resize box and should do the same when text is removed, but doesn't do this

**To Reproduce**
```
https://github.com/qarmin/czkawka.git
cd czkawka_gui_orbtk
cargo build --release
cd ../target/debug/cargo_gui_orbtk
```
2. Press any key for a long time to resize box
3. Remove all input

**Screenshots**
![jfile](https://user-images.githubusercontent.com/41945903/92412222-5a6aa080-f14b-11ea-8a53-1047023d7277.gif)

**Desktop (please complete the following information):**
Ubuntu 20.04 X11

**Comment by FloVanGH** [comment]
This is not a bug it depends on the configuration and or layout. You can fix this multiple ways e.g. by setting `width` or `max_width` on the `TextBox`.
