### ISSUE TITLE
[Question] Why is Image::from_rgba_image not a public function?

### ISSUE THREAD

**Issue by poutyface** [redox-os/orbtk#327]
It is a convenient function to set Image::ImageBuffer data to ImageWidget.image.

https://github.com/redox-os/orbtk/blob/00f44b943333e9683cc1cf9441643b353dd7756d/crates/render/src/raqote/image.rs#L45

**Comment by FloVanGH** [comment]
This is a mistake. I will fix this today.

**Comment by poutyface** [comment]
@FloVanGH thanks!

**Comment by FloVanGH** [comment]
done!
