### ISSUE TITLE
Alpha3: Want a way to force update in next loop

### ISSUE THREAD

**Issue by tysonstewart** [redox-os/orbtk#336]
# Context

This is somewhere between a feature request and a bug. I want to use a Grid widget/layout to show icons in a way similar to most file explorers. To do this, I want to use fixed size rows and columns and calculate the number needed based on the size available which is to say the bounds of the widget.

# Problem description & Solution

As mentioned above, in order to calculate the number of rows and columns, the widget must know its size. However, the size isn't calculated until the layout system runs. Modifying the widget after layout doesn't work (and in fact should likely be prevented as it results in some unexpected behavior). In alpha2, this wasn't an issue because the state was updated frequently. This changed in alpha3, probably for performance reasons. Now updates are only triggered when the widget is considered dirty, and all dirty statuses are reset after rendering, so any changes made or events triggered after their corresponding systems have run are not reflected until something external happens.

Possible solution: Add a post_render method to State that gets run after render and after dirty statuses have been cleared, which would allow developers a way to force another update when necessary. Alternatively, a much more narrow solution to my problem would be to calculate the bounds of a widget and set that property before the State's update method is called.

Workaround: For my problem, I can calculate bounds based on the initial window size, pass them to the widget on creation, and set the bounds property manually in the init method.

**Comment by FloVanGH** [comment]
Hi,
what you can do is to trigger a redraw, this will also rub a ne loop.

```rust
ctx.send_window_request(WindowReqeust::Redraw);
```

There will come some updates to do such things easier.

**Comment by tysonstewart** [comment]
Thank you for the suggestion! I didn't know about this. I tried using it in `update_post_layout` and it didn't work. Does it use the same event system that gets cleared after render?

**Comment by FloVanGH** [comment]
It goes direct through the window shell.
