### ISSUE TITLE
Window Decorations: enable/disable functionality

### ISSUE THREAD

**Issue by freyvalk** [redox-os/orbtk#337]
# Context
I've been learning the API and while attempting the make a widget like application I ran into an issue with trying to disable window decorators. I was not able to find any functionality to do this in the API.
Used in situations where a window's title-bar/decorations inhibits the usability/aesthetics of an application

# Problem description & Solution
As far as I can tell OrbTK has no ability to request the window manager to disable title-bars/window decorations.
This makes it a non starter for certain "widget like" applications where the window decorations can get in the way.

# Examples and MockUps
In the GDK you can call [gdk_set_window_decorations()](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-decorations) with 0 as the input. This disables all window decorations.

Similar functionality is in SDL's [SDL_NOFRAME](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetvideomode.html) flag for the SDL_SetVideoMode function.
What this function does with this flag enabled is try to _"return a window"_ that that doesn't have a title-bar or border.

**Comment by FloVanGH** [comment]
@freyvalk you can set `Window::new().borderless(true)`

**Comment by freyvalk** [comment]
Thank you,
I think I've found the source of the confusion.
Calling orbtk::Window::borderless(true) while building the window works as expected on ubuntu w/ xfce or gnome.
I tested it on windows and it quite literally disables the borders of the windows without disabling the title-bar.
I suspect this is an upstream issue, but haven't looked into the code yet.

**Code:**
```rust
use orbtk::prelude::*;

fn main() {
    Application::new()
        .window(|ctx| {
            Window::new()
                .title("OrbTk - minimal example")
                .position((100.0, 100.0))
                .size(420.0, 730.0)
                .borderless(true)
                .child(TextBlock::new().text("OrbTk").build(ctx))
                .build(ctx)
        })
        .run();
}
```
Cargo.toml
```
[package]
name = "test-tk"
version = "0.1.0"
authors = ["Freya"]
edition = "2018"

[dependencies]
orbtk = "0.3.1-alpha3"
```

**Example Windows:**
[![https://imgur.com/741pN3i.png](https://imgur.com/741pN3il.png)](https://imgur.com/741pN3il.png)
**Example Ubuntu:**
[![https://imgur.com/8N98Tr2.png](https://imgur.com/8N98Tr2l.png)](https://imgur.com/8N98Tr2l.png)
