### ISSUE TITLE
Image loading from file is broken

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#338]
**Describe the bug**
Cannot load images into ImageWidgets, looks like the loading mechanism cannot deal with windows paths.
it panics with 
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Could not load image width path: \"res/orbtk-space.png\""', crates\render\src\raqote\image.rs:96:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**To Reproduce**
Compile and run the following code snippet:

```rust
use orbtk::prelude::*;

fn main() {
    // use this only if you want to run it as web application.
    orbtk::initialize();

    Application::new()
        .window(|ctx| {
            Window::new()
                .title("OrbTk - image example")
                .position((100.0, 100.0))
                .size(800.0, 420.0)
                .child(ImageWidget::new().image("res/orbtk-space.png").build(ctx))
                .build(ctx)
        })
        .run();
}
```

**Expected behavior**
The image should appear on the screen

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version latest

**Comment by FloVanGH** [comment]
fixed
