### ISSUE TITLE
OrbTk TextInput widgets like TextBox and PasswordBox could't call the local input method

### ISSUE THREAD

**Issue by lixiaoce** [redox-os/orbtk#341]
I could't call my local input method when TextBox got focus. This problem leads to only English characters could be typed. Local input method should be called automatically like this(MS Chinese Input Method):
![other](https://user-images.githubusercontent.com/17565330/93707497-bbd63a80-fb61-11ea-8734-0235398c2422.jpg)

**Comment by lixiaoce** [comment]
By the way, chinese charaters are displayed correctly because I have already added my Font(.ttf file) to the project.
![other2](https://user-images.githubusercontent.com/17565330/93707998-7ae02500-fb65-11ea-88c7-c721a0d26636.jpg)

**Comment by kivimango** [comment]
Hello ! Thank you for reporting.
What is the name of the file font are you using ? Or can you provide a download link?
I would like to add it to Orbtk so at least we could display chinese characters.

**Comment by lixiaoce** [comment]
I wouldn't advise you to use this font because of its licensing agreement. https://www.foundertype.com/index.php/FontInfo/index/id/217, **it's NOT a free font.**
Some open source fonts are a better fit for this project. Like https://source.typekit.com/source-han-serif/ and its github https://github.com/adobe-fonts/source-han-serif

**Comment by lixiaoce** [comment]
> 
> 
> Hello ! Thank you for reporting.
> What is the name of the file font are you using ? Or can you provide a download link?
> I would like to add it to Orbtk so at least we could display chinese characters.
I wouldn't advise you to use this font because of its licensing agreement. https://www.foundertype.com/index.php/FontInfo/index/id/217, **it's NOT a free font.**
Some open source fonts are a better fit for this project. Like https://source.typekit.com/source-han-serif/ and its github https://github.com/adobe-fonts/source-han-serif

**Comment by lixiaoce** [comment]
> 
> 
> Hello ! Thank you for reporting.
> What is the name of the file font are you using ? Or can you provide a download link?
> I would like to add it to Orbtk so at least we could display chinese characters.

I wouldn't advise you to use this font because of its licensing agreement. https://www.foundertype.com/index.php/FontInfo/index/id/217, **it's NOT a free font.**
Some open source fonts are a better fit for this project. Like https://source.typekit.com/source-han-serif/ and its github https://github.com/adobe-fonts/source-han-serif
