### ISSUE TITLE
Question : how to update without on_click() ?

### ISSUE THREAD

**Issue by qq389146213** [redox-os/orbtk#342]
I want to create an app that shows the time.
how to update widget without on_click() ?

impl State for MainViewState {
    fn init(&mut self, r: &mut Registry, ctx: &mut Context) {
	    println!("init");
	}

    fn update(&mut self, _: &mut Registry, ctx: &mut Context) {
        //how to update the time without mouse click
    }

what I mean is I want automatic update but i can`t find any method like :
on_load() or on_start() or on_create() to trigger the update
also there is no timer in default widgets

**Comment by FloVanGH** [comment]
You can check https://github.com/redox-os/orbtk/issues/305 there is an example. A more comfortable way will come.
