### ISSUE TITLE
`Selected:` in widgets example is only updated after theme toggle

### ISSUE THREAD

**Issue by arctic-alpaca** [redox-os/orbtk#347]
Hello,
**Describe the bug**
Using the widgets example, the `Selected:` text under the item list in only updated when the theme toggler in the bottom left is used. It also starts to count at 0 which is a bit confusing since the items start at 1.
**To Reproduce**
1. git clone https://github.com/redox-os/orbtk.git
2. cd orbtk
3. cargo run --example widgets --release
4. click on `Select Item 5`
5. nothing happens
6. toggle `Toggle theme`
7. `Selected: 4` is displayed

**Expected behavior**
After clicking on a item in the list, the text underneath should update to the corresponding number. E.g. click on `Select Item 5` should display `Selected: 5`

**Desktop (please complete the following information):**
 - OS: Win10 1909

**Additional Information**
The one off (4 instead of 5 displayed) behavior is present in alpha3. The not updating/displaying problem is new in alpha4.

**Comment by FloVanGH** [comment]
fixed

**Comment by arctic-alpaca** [comment]
Thanks!
Is it alright if I create a PR to change the behavior to display the same number as the selected item displays?

**Comment by FloVanGH** [comment]
Yes sure. Thank you.
