### ISSUE TITLE
How can I rotate/translate a RenderContext2D to draw vertical text?

### ISSUE THREAD

**Issue by arctic-alpaca** [redox-os/orbtk#351]
Hello,
for the [plotters backend](https://github.com/arctic-alpaca/plotters_in_orbtk) I'm working on, I need to be able to draw text in different rotations. I tried the `set_transform` method but I can't get it right.

This is what I thought might work, but didn't: 
```rust
let mut degree = match style.transform() {
    FontTransform::None => 0.0,
    FontTransform::Rotate90 => 90.0,
    FontTransform::Rotate180 => 180.0,
    FontTransform::Rotate270 => 270.0,
} / 180.0
    * std::f64::consts::PI;

if degree != 0.0 {
    self.render_ctx.save();
    self.render_ctx.set_transform(
        degree.cos(),
        -degree.sin(),
        degree.sin(),
        degree.cos(),
        x as f64,
        y as f64,
    );
    x = 0;
    y = 0;
}

...

if degree == 0.0 {
    self.render_ctx.restore();
}
```

Here are some examples of other plotters backends:
- [Cairo](https://github.com/plotters-rs/plotters-cairo/blob/master/src/backend.rs#L278)
- [SVG](https://github.com/plotters-rs/plotters-svg/blob/master/src/svg.rs#L384)
- [Canvas](https://github.com/plotters-rs/plotters-canvas/blob/master/src/canvas.rs#L237)

**Comment by FloVanGH** [comment]
It's possible that the implementation in OrbTk is wrong. I will check it.

**Comment by arctic-alpaca** [comment]
I'm not really sure whether or not what I tried should work, I tried to emulate what other backends do but I'm not sure if that's applicable to OrbTk.
Thanks for looking into it.

**Comment by FloVanGH** [comment]
Yeah it's still under development and not yet stable. But your feedback and findings are valuable and helps use to improve OrbTk, thanks. I hope we will find more contributors, that will make it easier to work on new features and fix bugs.

I found the source of your problem. The text is drawn with `ruststype` and the implementation not yet take use of the transformation. We have to implement it in our raqote backend. I will check we can implement it in the next few day. I hope that is ok.

**Comment by arctic-alpaca** [comment]
> I will check we can implement it in the next few day. I hope that is ok.

Absolutly, it's great how responsive you're handling this project. Thank you very much for your hard work!

**Comment by FloVanGH** [comment]
Thank you. You're welcome.
