### ISSUE TITLE
Pager right arrow in showcase example disappears when resizing horizontally

### ISSUE THREAD

**Issue by arctic-alpaca** [redox-os/orbtk#354]
**Describe the bug**
Depending on the window size, the right arrow of the pager in the showcase example disappears, see screenshots for clarification.

**To Reproduce**
1. git clone https://github.com/redox-os/orbtk.git
2. cd orbtk
3. cargo run --example showcase --release
2. resize window to the right until the arrow disappears
3. resize window downwards till the arrow reappears

**Expected behavior**
Arrow is visible at all times.

**Screenshots**
Visible:
![visible](https://user-images.githubusercontent.com/67190338/94198595-c83afa00-feb7-11ea-8573-f903b100632d.PNG)

Partly visible after resizing to the right:
![partly](https://user-images.githubusercontent.com/67190338/94198614-d12bcb80-feb7-11ea-918a-53d3838da6a6.PNG)

Not visible after resizing further to the right:
![not_visible](https://user-images.githubusercontent.com/67190338/94198635-dee15100-feb7-11ea-86e1-a1418ad69bee.PNG)

Visible again after resizing downwards:
![visible_again](https://user-images.githubusercontent.com/67190338/94198658-e99be600-feb7-11ea-926a-fef678a212d7.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 1909

**Comment by FloVanGH** [comment]
fixed
