### ISSUE TITLE
Add on_mouse_over callback

### ISSUE THREAD

**Issue by kivimango** [redox-os/orbtk#372]
# Context
It would be good to have a callback when a mouse's position enter's a widget's bounds to change a border or background color.

**Comment by FloVanGH** [comment]
What do you think about mouse_enter, and mouse_leave callbacks. And a hover flag?

**Comment by kivimango** [comment]
Yes, we will need a mouse_leave callback too, I don't think a hover flag is necessary since mouse_enter implicitly states that 
```hover=true```, right ?

**Comment by FloVanGH** [comment]
On enter and leave you could be trigger stuff. And hover would be an additional widget property.

**Comment by FloVanGH** [comment]
With the callbacks you can react in the moment the mouse enters or leaves and if you only want to check if the the mouse is over a widget (without the whole callback logic) you could read the hover flag. The flag could e.g. be used to change the background.

**Comment by kivimango** [comment]
Thx.
That was fast.
