### ISSUE TITLE
Widget example in README no longer exists

### ISSUE THREAD

**Issue by dvente** [redox-os/orbtk#385]
**Describe the bug**
In the main README of the repo, under Run Examples it says: 
> You can start the widgets example by executing the following command:
>
>```
>cargo run --example widgets --release
>```

however running this gives the output: 
``` 
error: no example target named `widgets`
```
trying to run it with any of the files present in the example folder works fine. Not a huge deal but should probably be updated

**To Reproduce**
1. Clone and cd into the repo
2. run `cargo run --example widgets --release`

**Expected behavior**
The commands to run an example in the README actually run an example.

**Comment by FloVanGH** [comment]
Fixed. Thank you for the report.
