### ISSUE TITLE
Wasm2js cannot be installed for cargo-node version

### ISSUE THREAD

**Issue by LuminousLizard** [redox-os/orbtk#403]
**Describe the bug**
I cannot run the cargo-node versions with the commands provided in the Readme.md.
I have following error message:
```
[luminouslizard@lumi orbtk-develop]$ cargo node run --target android --example showcase     

install wasm2js
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luminouslizard/.npm/_logs/2020-11-26T21_42_19_959Z-debug.log
```
If I run the command with sudo (to give the permission), following message is displayed:
`error: no override and no default toolchain set`

**To Reproduce**
The native desktop version works perfect.
Following the steps provided in the Readme.md.
I installed cargo-node, NodeJS and npm. 

**Desktop:**
 - OS: Linux 5.9.10 Manjaro KDE
 - Browser Firefox 83.0
 - rustc 1.48.0 (7eac88abb 2020-11-16)
 - rustup 1.22.1 (b01adbbc3 2020-07-08)
 - NodeJS 15.2.1-1
 - npm 6.14.8-2

**Comment by FloVanGH** [comment]
Hi thank you for your report. Can you add the issue to https://github.com/FloVanGH/cargo-node please?

**Comment by LuminousLizard** [comment]
Will do.
