### ISSUE TITLE
Unable to Update Text

### ISSUE THREAD

**Issue by Autofire** [redox-os/orbtk#404]
Hi! I'm having some issues getting OrbTk to behave. I'm trying to build a front-end for a program which will "encrypt" files. (Ok, it's not planned to be excellent encryption; this is meant to be a class project demonstrating things in Rust, so this isn't meant to be a super robust encryption system. That's all beside the point, though.)

I'm struggling with getting the text to update in my program in response to a message. I'm really confused because otherwise, everything seems to be working. I've gotten almost the exact same logic working in a watered-down example program, but... that hasn't helped much.

At the moment, when I run it, I get this after dragging and dropping the highlighted file in. I want the "No file" text to change to the file's path. (Ultimately it will change to the file's name, but that comes later.)
![image](https://user-images.githubusercontent.com/7464159/100395148-a7486f80-2ff4-11eb-9174-0fcb99f63d6d.png)

[This is the simplified example](https://gist.github.com/Autofire/895c471cef9b9c886b9d6d9f6bcb80bc) which _does_ work. It's based on the OrbTk example with multithreading, except I played with it some.

[This is the project I am working on.](https://gist.github.com/Autofire/f205afb1df6e7a33872fe125924846c6) In retrospect I should have just uploaded my repo to GitHub; I'll do that if I keep having issues.

**Comment by FloVanGH** [comment]
Hi, thank you for your interested. I debugged a little bit inside your example. And it's a crazy behavior. If I check the `text` property of the `TextBlock` inside of the `update_post_layout` method of the state the text is still correct, but on the `TextRenderObject`the text is again `No file`. The counter example on the showcase works similar to your example and it works. I think I need some time to debug this more. Maybe it could be a bug. I let you know when I found something.

**Comment by FloVanGH** [comment]
I found the source of the issue and have a workaround for you. The problem depends on the localization mechanism of OrbTk. In your example it reads the wrong string for the `TextBlock`. I'm will create a new issue for this, and will fix this issue soon. 

In the meantime you can set `.localizable(false)` on your `TextBlock` and it should work.

**Comment by FloVanGH** [comment]
#405

**Comment by Autofire** [comment]
Ahh, that works! Thank you, this helps a lot! I probably would have never found this workaround on my own.

**Comment by FloVanGH** [comment]
You're welcome :-)
