### ISSUE TITLE
Having a widget send a message to its parent pager?

### ISSUE THREAD

**Issue by Autofire** [redox-os/orbtk#406]
This is not so much a bug or an error I'm having trouble with, but rather I'm just not sure how to structure this in a sane way.

Long story short, I want to have a Pager, and inside some of those pages will be buttons which will make the pager switch to different pages.

As far as I can tell, that seems impossible because, in order to create a lambda which makes the pager switch pages, I need to have the pager built. However, in order to put a button inside a pager, I need to do that before I build the pager.

Put another way, is there some way to change this code so that the button is a child of the pager?

```rust
let pager = Pager::new()
    .child(TextBlock::new().text("Page 1").build(ctx))
    .child(TextBlock::new().text("Page 2").build(ctx))
    .build(ctx);

let next_button = Button::new()
    .enabled(("next_enabled", pager))
    .text("next")
    .on_click(move |states, _| {
        states.send_message(
                PagerAction::Next,
                pager // This is the part that prevents me from just putting the button inside the pager
        );
        true
    })
    .build(ctx);
```

My guess is no, due to the way borrowing and references work in Rust. I am also passing a message along to [my state object](https://github.com/Autofire/BananaEncryption/blob/master/src/main_state.rs)... could I use that to pass a message along to the pager? If so, how do I get the pager in such a way that allows me to modify it and/or pass a message to it?

Or is passing messages the wrong approach entirely? I remember reading in another issue that message passing was getting deprecated, but I have no idea what else to use.

**Comment by FloVanGH** [comment]
Hi, here is an example how you can archive to add buttons to the pager:

```rust
let pager = Pager::new()
    .build(ctx);

let next_button = Button::new()
    .enabled(("next_enabled", pager))
    .text("next")
    .on_click(move |states, _| {
        states.send_message(
                PagerAction::Next,
                pager // This is the part that prevents me from just putting the button inside the pager
        );
        true
    })
    .build(ctx);

ctx.append_child(pager, next_button);
```
The `BuildContext` allows you to add children to a widget explicit. You can also have a container widget (e.g. a grid or stack layout) inside of the pager and add the button to the container.

**Comment by Autofire** [comment]
Ah, that works! Thank you so much!
