### ISSUE TITLE
Unable to compile examples: `sdl2-sys` fails to download

### ISSUE THREAD

**Issue by wucke13** [redox-os/orbtk#410]
**Describe the bug**
The command `cargo run --example showcase --release` fails with

```
error: failed to run custom build command for `sdl2-sys v0.34.3`

Caused by:
  process didn't exit successfully: `/home/wucke13/documents/projects/rust/orbtk/target/release/build/sdl2-sys-d600d0eb48651eb0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Command 'curl' failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
', /home/wucke13/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-sys-0.34.3/build.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**
1. run `cargo run --example showcase --releas` on latest develop branch

**Expected behavior**
The thing compiles at least

**Desktop (please complete the following information):**
 - OS: NixOS 20.09

**Comment by igotfr** [comment]
@wucke13 it worked for me like this:

in my orbtk project I created a examples folder, inside the examples folder I created a file, I created stack.rs (https://github.com/redox-os/orbtk/blob/develop/examples/stack.rs)

in terminal I typed:
$ cargo run --example stack --release

**Comment by wucke13** [comment]
Why would that affect the build of the `sdl` lib, @cindRoberta ?

**Comment by fneddy** [comment]
this happens on my nixos to. But i think this is a problem in **sdl2-sys** crate

**Comment by pvshvp-oss** [comment]
The example fails to build on Arch Linux too:

``` rust
$ cargo run --example showcase --release
...
...
error: failed to run custom build command for `sdl2-sys v0.34.5`

Caused by:
  process didn't exit successfully: `/home/user/temp/orbtk/target/release/build/sdl2-sys-eac5ee27e416feb0/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Command 'curl' failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
  curl: (28) Failed to connect to libsdl.org port 443: Connection timed out
  ', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-sys-0.34.5/build.rs:61:17
```

**Comment by wucke13** [comment]
@fneddy Well, yes and no. For me it is like this: For over half a year now, if I think of viable solutions to building a native GUI in Rust, when I see orbtk, I just remember "nay, doesn't even work in their own demo". I'm probably not the only one. So regardless of from where it originates, this issue renders orbtk useless for one of it's primary use cases: cross platform native GUI. So if there is a workaround (like forking SDL and patching the fork), it's well worth it.

**Comment by pwil3058** [comment]
I get this problem on my laptop but not my desktop.  Both are latest version of Linux Mint.  Looking at the repository the rust-sdl2/sdl2-sys/build.rs file seems to be very complex.

**Comment by pvshvp-oss** [comment]
Perhaps this is related: https://github.com/Rust-SDL2/rust-sdl2/issues/1062

**Comment by ghost** [comment]
I tested it on macOS, Windows, Ubuntu and on Manjaro and never had the same issues. 

@shivanandvp it could be related to that issue. OrbTk builds sdl2 bundled as default but it is also possible to disable this feature in OrbTk.

**Comment by xiaohulu** [comment]
I have the same error on Windows 11

```
error: failed to run custom build command for `sdl2-sys v0.34.5`

Caused by:
  process didn't exit successfully: `D:\sources\xiaohulu\my-work\orbtk-ui\target\debug\build\sdl2-sys-0d3aa4257045a2e8\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', C:\Users\xiaohulu\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\sdl2-sys-0.34.5\build.rs:159:82
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ghost** [comment]
I have a solution for this issue. At the moment OrbTk is using the `bundled` Feature of the sdl2 es crate by default. With this sdl2 source code is build within OrbTk. I will make this feature optional. This mean instead of build sdl2 with OrbTk you can use your sdl2-lib installation and the issue should not be occurs.

**Comment by ghost** [comment]
On default OrbTk uses now an installed version of `sdl2` check https://github.com/Rust-SDL2/rust-sdl2. Alternative it is possible to build sdl2 with OrbTk using the bundled features `cargo run --example showcase --features bundled`
