### ISSUE TITLE
[ Not compile ]

### ISSUE THREAD

**Issue by igotfr** [redox-os/orbtk#419]
**Desktop (please complete the following information):**
 - OS: Fedora 31 with i3wm

___

main_view.rs
```rust
use orbtk::prelude::*;

//use crate::MainState;

widget!(
  MainView {
    title: String
  }
);

impl Template for MainView {
  fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
    self.name("MainView").child(TextBlock::new().text(("title", id)).build(ctx))
  }
}
```

main.rs
```rust
use orbtk::prelude::*;

//pub use self::main_state::*;
pub use self::main_view::*;

//mod main_state;
mod main_view;

fn main() {
  Application::from_name("orb")
    .window(move |ctx| {
      Window::new()
        .title("orb")
        .position((100.0, 100.0))
        .size(372.0, 768.0)
        .resizeable(true)
        .child(MainView::new().title("Hello OrbTk").build(ctx))
        .build(ctx)
    })
    .run();
}
```

___

[notecomm@localhost orb]$ cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.33s
     Running `target/debug/orb`
thread 'main' panicked at 'StringComponentStore.get: internal downcast error', /home/notecomm/.cargo/registry/src/github.com-1ecc6299db9ec823/dces-0.3.0/src/component/string_component_store.rs:252:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

___

the problem is on text(("title", id)), when I use text("title") it works

**Comment by sandmor** [comment]
I also experimented this error multiple times is horrible to debug it. It happens every time that you use an not acceptable value type for a property I would refer to it as the NullPointerException of OrbTk, I think that the same behavior happens if you forget to set an must-have prop. The error is tracked down to `dces` a dep so I'm insecure of how to correct it.
Maybe @FloVanGH has some idea

**Comment by ghost** [comment]
@cindRoberta sorry for the late response. What is your OrbTk version? If it is the latest from crates.io I think I know the error. On the latest crates.io the type of `text` of `TextBlock` is `String16` and not `String`. We changed it to `String`, but this update is now only available on the `develop` branch right now. 

I'm also working on a better error management in DCES.
