### ISSUE TITLE
Window resizes incorrectly (sway)

### ISSUE THREAD

**Issue by vessd** [redox-os/orbtk#422]
**Describe the bug**
Are tiling window managers supported?
I tried playing around with the minimal example from the readme, but it doesn't display correctly.

**To Reproduce**
Run code from readme.
<details>
  <summary>Code</summary>

```
use orbtk::prelude::{Alignment, Application, Brush, Color, TextBlock, Widget, Window};

fn main() {
    Application::new()
      .window(|ctx| {
          Window::new()
              .title("OrbTk - minimal example")
              .v_align(Alignment::Stretch)
              .h_align(Alignment::Stretch)
              //.position((100.0, 100.0))
              //.size(420.0, 730.0)
              .resizeable(true)
              .background(Brush::SolidColor(Color::rgb(0, 0, 0)))
              .child(TextBlock::new().text("OrbTk").build(ctx))
              .build(ctx)
      })
      .run();
}
```

</details>

**Expected behavior**
Correct display in the allocated space.

**Screenshots**
Before focusing:
<details>
  <summary>Image</summary>

![изображение](https://user-images.githubusercontent.com/8783865/103917805-15697180-511f-11eb-8957-f82a972b08c3.png)

</details>

After focusing:
<details>
  <summary>Image</summary>

![изображение](https://user-images.githubusercontent.com/8783865/103918076-64170b80-511f-11eb-8506-880f2552032b.png)

</details>

**Desktop:**
 - OS: Arch Linux
 - DE: sway
 - OrbTk: 0.3.1-alpha3

**Comment by ghost** [comment]
Thank you for your report. Tiling window managers should be supported. It worked for i3. I will check if it again.

**Comment by vessd** [comment]
I have checked examples from the `develop` branch, it looks like the problem has been fixed already. Sorry for disturbing.
