### ISSUE TITLE
How to handle a click event on a container?

### ISSUE THREAD

**Issue by matthewashton-k** [redox-os/orbtk#425]
Basically, the title says it all. I'm just trying to figure out how to use the insert_handler method to handle click events on a widget, but I cant figure out how to use it at all. Somehow I need to create an EventHandler, but I don't know how to do that either. any help would be greatly appreciated.

**Comment by kivimango** [comment]
Hello.
Your widget should "extend" a KeyDownHandler.After that, you could define an on_key_down() callback in its template, and decide what you want to do with the key event.
The closure will be called when the widget is focused and there is a key strike.

```rust
widget!(MyWidget: KeyDownHandler {
    focused: bool
    ...
);


impl Template for MyWidget {
    fn template() {
        self.name("MyWidget")
        .on_key_down(move |ctx, key_event| -> bool {
            println("received key event: {}, key_event.key);
            false
        }
        )
    }
}

**Comment by matthewashton-k** [comment]
Ah, ok that makes sense now, thank you.
