### ISSUE TITLE
Compile Failing for multi_window Example

### ISSUE THREAD

**Issue by jgrussell** [redox-os/orbtk#430]
**Describe the bug**
The [multi_window](https://github.com/redox-os/orbtk/blob/develop/examples/multi_window.rs) example is failing to compile in the same manor [reported with details](https://github.com/redox-os/orbtk-template/issues/4) in the [orbtk-template](https://github.com/redox-os/orbtk-template) repository.

**To Reproduce**
1. Start new project with `cargo new orbtk-multi-window`
2. Copy https://github.com/redox-os/orbtk/blob/develop/examples/multi_window.rs to `orbtk-multi-window/src/main.rs`
3. Edit orbtk-multi-window/Cargo.toml to add `orbtk = { git = "https://github.com/redox-os/orbtk.git", branch= "develop" }` dependency 
4. `cd orbtk-multi-window && cargo run`
5. See errors, same as reported in [reported with details](https://github.com/redox-os/orbtk-template/issues/4) in the [orbtk-template](https://github.com/redox-os/orbtk-template) repository.

**Expected behavior**
Example window displayed.  

The [Minimal Example](https://github.com/redox-os/orbtk/blob/develop/examples/minimal.rs) does still produce expected behavior.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser:  N/A, using `cargo run` from command line
 - Version:  My entire rust environment is less than two weeks old, created with rustup.

**Comment by jgrussell** [comment]
A quick and dirty fix for this is to add `use orbtk::api::macros::*;` at the top of the https://github.com/redox-os/orbtk/blob/develop/examples/multi_window.rs file.

If anyone from this project would care to provide direction as to how this should be fixed more globally, I would be happy to try and tackle it myself.

Fair warning, I am new to Rust and have never contributed to an open source project.

**Comment by rzerres** [comment]
I can't reproduce this on active branch `develop`.
Please open again, if you still have issues to compile the example.
