### ISSUE TITLE
Sdl2 panics immediately on running an application

### ISSUE THREAD

**Issue by matthewashton-k** [redox-os/orbtk#431]
**Describe the bug**
I'm trying to make a simple application, but running it fails with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "No available video device"', /home/xxx/.cargo/git/checkouts/orbclient-519a630a59c70d98/904157c/src/sys/sdl2.rs:26:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
Try to run any of the examples with the most recent version of orbtk from the develop branch

**Desktop:**
 - OS: Ubuntu 20

**Additional context**
I tried installing libsdl2-dev but that didnt fix the problem.
I also installed libxkbcommon-dev libwayland-cursor0 libwayland-dev and that didn't help either.

**Comment by y15un** [comment]
I also had this problem in the past, but now it builds just fine. In the between, I did install these (on Solus): `libx11-devel`, `libxext-devel`, `freetype2-devel`. I think it's the `libxext-devel`.

**Comment by matthewashton-k** [comment]
huh, well for some reason its working now, Im not sure if it was just a recent commit that fixed it or not.
