### ISSUE TITLE
Hi does this support wayland and other questions?

### ISSUE THREAD

**Issue by Joe23232** [redox-os/orbtk#443]
Hi I have some questions regarding this project.

1. Does this support wayland or x11 or both?
2. Does it have retained graphics or immediate graphics?
3. How does it differ to the GUI crate [`iced`](https://github.com/hecrj/iced)

**Comment by ngortheone** [comment]
Hey @Joe23232 

It does support both. I ran orbtk on sway (wayland) and on x11 KDE
