### ISSUE TITLE
Impossible to select the last tab after the previous last tab was closed

### ISSUE THREAD

**Issue by AndersonDeMatos** [redox-os/orbtk#479]
When we close the last tab on the showcase example, it is impossible to select the tab that was just before that (it is the last tab now). For example, if there are 3 tabs and we close the third one, only two will remain (obviously), but we can't select the  second one (now the last one) without first selecting the first tab.
If there are only 2 tabs and we close the last tab, it will be impossible to see the contents of the remaining tab, it will be constantly inactive.

1. Run the showcase example;
2. Close the last tab;
3. Try to click on the tab that is now the last one;

I noticed that when click on the close icon of an inactive tab, it gives that tab the focus before closing it. It would be good if we could close an inactive tab without changing focus first.
If the last tab already has the focus when we click the close button, forcing the focus to change to the previous tab could solve the problem.

**Desktop**
 - Linux Mint 20.3 Cinnamon
 - Linux Kernel: 5.4.0-97-generic
 - Cinnamon version: 5.2.7
 - Processor: AMD FX-8150 
 - RAM: 16 GB
 - Graphics Card: NVIDIA GT-710 1GB RAM

**Comment by rzerres** [comment]
fixed. Will send a PR and merge.

**Comment by rzerres** [comment]
Bugfix merged.
