### ISSUE TITLE
About other languages

### ISSUE THREAD

**Issue by ShirasawaTopaz** [redox-os/orbtk#482]
What makes me sad is that Orbtk still doesn't support Chinese
It seems that not only Chinese, but also Japanese
When will there be support for them, please?

**Comment by Cy6er7um** [comment]
Chinese/Korean/Japanese characters r not supported now, because orbtk use the `Roboto` font which does not provide for langs like Chinese. #163

**Comment by moon989** [comment]
> What makes me sad is that Orbtk still doesn't support Chinese It seems that not only Chinese, but also Japanese When will there be support for them, please?

you can regist a chinese font ,replace default Roboto font

**Comment by rzerres** [comment]
Just for clarification:

I know, this is a totally unsatisfactory situation.
But to be clear: we can't and will not attempt to include giant amount of font files into the toolkit. This simply will not overcome the given shortcoming.

If you are eager, `OrbTk` already offers a mechanism to include and reference your preferred native font via ithe theming engine. E.g.this enables you, to extend the font path pointing to the storage path of your font file. This will be checkt and referenced at compile time. ... Consult the examples or the book ....

As a more idiomatic development goal:

* enhance font handling
   We should be able to incorporate crate [`fontdb`](https://github.com/RazrFalcon/fontdb). This will enable us to use system installed fonts (Multi-Platform aware). 
   This is especially important to open `OrbTk` for Arabic, Indian-, Korean-, Hebrew-, Chinese
, Japan languages et. al., without incorporating giant font files into the framework itself.

Would love, if anybody is interested in that topic and like to volunteer. Open for an open discussion on that issues. Remember: we are developing noncommercial and without any funding! 

We do have matter most based redox chat channel for further online discussion.

**Comment by jluwoniu** [comment]
> 



> > What makes me sad is that Orbtk still doesn't support Chinese It seems that not only Chinese, but also Japanese When will there be support for them, please?
> 
> you can regist a chinese font ,replace default Roboto font

how regist a chinese font?

**Comment by slondr** [comment]
> If you are eager, OrbTk already offers a mechanism to include and reference your preferred native font via ithe theming engine. E.g.this enables you, to extend the font path pointing to the storage path of your font file. This will be checkt and referenced at compile time. ... Consult the examples or the book ....

Could you clarify that somewhat? As far as I can tell, none of the examples use a custom font, and searching the book for "font" only brings up either how to use the built-in icon fonts or a blurb in the [tinyskia section](https://redox-os.github.io/orbtk-book/en/ch02-04-workspace-orbtk-tinyskia.html?highlight=font#workspace-orbtk_tinyskia) about how there are no good font rasterizers in Rust right now.
