### ISSUE TITLE
Suggestion: CheckBox

### ISSUE THREAD

**Issue by BojanKogoj** [redox-os/orbtk#51]
Create a CheckBox widget

Visually:
![image](https://user-images.githubusercontent.com/634075/32406102-7a70e09e-c172-11e7-89ea-a511643b9f9c.png)

Example usage:
```rust
    let cb = CheckBox::new();
    cb
        .text("Start with Sunday")
        .checked(true) // Default false
        .checkbox_right(true) // For right side example, default false
        .on_checked_changed(... {
        
        });
```

Detailed UI

![checkbox](https://user-images.githubusercontent.com/634075/32406231-08a0c8a0-c175-11e7-9a27-b462d983a2e2.png)

[HTML example](https://codepen.io/bojank/pen/rYeJpG) (non interactive) of the above picture

**Comment by BojanKogoj** [comment]
Example in application

![image](https://user-images.githubusercontent.com/634075/32406570-445639ec-c17b-11e7-8449-c0a5f22c275b.png)

**Comment by FloVanGH** [comment]
It would be nice to use a Icon-Font e.g. for the CheckBox Icon. For the start we could use a OS Icon-Font like the Material Icon-Font from Google.
