### ISSUE TITLE
Button default sizes

### ISSUE THREAD

**Issue by BojanKogoj** [redox-os/orbtk#53]
By default, Button has no size or text offset. We should provide defaults if those are not set, so you don't need to set them every time. It would also help with having a "standard" button size in all apps.

I suggest the following:
- Button height: 35px
- Text offset: 11px
- Button width depends on text

![button-defaults](https://user-images.githubusercontent.com/634075/32414306-169f719a-c224-11e7-9dbb-26b9fe3e6d8b.png)

This is current implementation
```rust
        let b = Button::new();
        let text = "Hello world";
        b
            .text(text)
            .size(11 + text.len() as u32 * 8 + 11, 35)
            .position(50, 80)
            .text_offset(11, 11);
```

After this change it would only be

```rust
        let b = Button::new();
        b
            .text("Hello world")
            .position(50, 80);
```

**Comment by FloVanGH** [comment]
Could be closed. Implemented with #74.
