### ISSUE TITLE
Suggestion: ComboBox

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#60]
<img width="655" alt="combobox" src="https://user-images.githubusercontent.com/6715107/33397663-9e589c16-d54c-11e7-93d7-89d6274dd08c.png">

**Example use**

```rust
let combo_box = ComboBox::new();
list.position(5, 5).size(266, 28);

for i in 0..5 {
    let item = ComboBoxItem::new(format!("Item {}", i));
    combo_box.push(&item);  
} 
```

**Comment by jackpot51** [comment]
That looks really good!

**Comment by FloVanGH** [comment]
Missing features:

- [ ]  Scrolling
- [ ]  Flyout placement (top / bottom)
- [ ]  Widget entries

**Comment by robbycerantola** [comment]
I'm trying to use ComboBox : if I place the widget using  .position(x,y)  when x is > 200 the entries are progressively chopped until they completely disappear.
I think there is something wrong when checking if the entry fits inside the flyout rect (or the Entry rect.width is not updated correctly).
