### ISSUE TITLE
Widget children

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#72]
The construction of a widget should be consists of other widgets as children. E.g. a button consists of a rectangle and a label.

https://www.ics.com/blog/creating-qml-controls-scratch

**Comment by BojanKogoj** [comment]
For debugging purpose we need widget tree, for example
``` 
Window (OrbTK)
|- StackLayout (Vertical)
|    |- Menu
|    |- Label
|    |- StackLayout (Horizontal)
|    |    |- TextBox
|    |    |- Button
|    |- Label
|    |- ProgressBar
|    |- ComboBox
|    |- Label
|    |- TextBox
|    |- Label
```
