### ISSUE TITLE
Declarative Uis

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#76]
Maybe it could be interesting to use a declarative language for building an UIs and new widgets. Compare Qml in Qt http://doc.qt.io/qt-5/qmlapplications.html and XAML in WPF https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-overview-wpf. A base for the orbtk declarative language could be RON https://github.com/ron-rs/ron.

**Comment by Vagdish** [comment]
May I add KV for Kivy as an example ? https://kivy.org/docs/guide/lang.html

**Comment by FloVanGH** [comment]
Thank you I'll take a look at it.
