### ISSUE TITLE
Doesn't work well with i3wm

### ISSUE THREAD

**Issue by vpzomtrrfrt** [redox-os/orbtk#77]
I haven't tried other window managers, but at least on i3, windows created with orbtk are floating, rather than tiling.  This is unexpected, as the default state is tiled for most other applications

**Comment by FloVanGH** [comment]
Could you test orbterm with i3 wm? If you observe the same behaviour there, than it could be a problem with orbclient.

**Comment by vpzomtrrfrt** [comment]
orbterm appears to work fine

**Comment by jackpot51** [comment]
Did you mark the window as resizable?

**Comment by jackpot51** [comment]
Here is an example:

```
Window::new_flags(Rect::new(-1, -1, width, height), "Editor", &[WindowFlag::Resizable]);
```

**Comment by vpzomtrrfrt** [comment]
That works, though the window seems to be manually resizable without the flag

**Comment by quadrupleslap** [comment]
Not sure if related, but this also happens with GTK for me.
