### ISSUE TITLE
TabsWidget

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbtk#97]
# Context

The TabWidget should be used in a navigation context.

# Problem description & Solution

The TabWidget should be used to organize different content on different views. The content should be switched by select from a list of items.

# Examples and MockUps

<img width="377" alt="image" src="https://user-images.githubusercontent.com/6715107/70080408-c7726800-1606-11ea-81c2-e4b189608f13.png">

**Comment by kivimango** [comment]
Im thinking of this:
```rust
TabView::new()
    .tab(
        .child(
             TextBlock::new().
             .text("Tab 1 content")
             .build(ctx)
        )
        .title("Tab 1")
        .index(0)
    ).build(ctx)
    .tab(
        .child(
             TextBlock::new().
             .text("Tab 2 content")
             .build(ctx)
        )
        .title("Tab 2")
        .index(1)
    ).build(ctx)
 .build(ctx)
```

like GridView.
When user clicks on one of the tab's header, the TabView widget will set the selected tab's `visible `property to `true`

**Comment by FloVanGH** [comment]
@kivimango what about a shorter version:

```rust
TabView::new()
    .tab(
        "Tab 1",
        TextBlock::new().
             .text("Tab 1 content")
             .build(ctx)
    )
    .tab(
       "Tab 2",
        TextBlock::new().
             .text("Tab 1 content")
             .build(ctx)
    )
 .build(ctx)
```

Index could be implicit generated.
